### ISSUE TITLE
[BUG]Business Hourly Reporting

### ISSUE THREAD

**Issue by colin99d** [unit8co/darts#1057]
**Describe the bug**
Using business hours fails when there are gaps in the data. Even when the hours are within "business hours". 
<img width="567" alt="Screen Shot 2022-07-04 at 9 34 46 AM" src="https://user-images.githubusercontent.com/72827203/177165781-77b80295-49e1-4685-8b50-6cc56b0a69d9.png">
Another interesting component of this issue is that the errors say that interval with freq="h" could not be filled, even though I set a freq of "BH". Below is the code to get the series (just to show that freq="BH"), and then the error. 
```
def get_series(data, target_col: str = None, is_scaler: bool = True):
    filler = MissingValuesFiller()
    filler_kwargs = dict(
        df=data,
        time_col="date",
        value_cols=[target_col],
        freq="BH",
        fill_missing_dates=True,
    )
    try:
        ticker_series = TimeSeries.from_dataframe(**filler_kwargs)
    except ValueError:
        # remove business days to allow base lib to assume freq
        filler_kwargs.pop("freq")
        ticker_series = TimeSeries.from_dataframe(**filler_kwargs)
```
<img width="880" alt="Screen Shot 2022-07-04 at 9 41 35 AM" src="https://user-images.githubusercontent.com/72827203/177166937-09f65663-851b-4ac5-bca9-162ae7d28913.png">

**To Reproduce**
Try creating a timeseries with the below data:
[1hour.csv](https://github.com/unit8co/darts/files/9039862/1hour.csv)

**Expected behavior**
I would expect the BH frequency to be detected and for that to be used.

**System (please complete the following information):**
 - Python version: 3.9.13
 - darts version: 0.20.0

**Comment by hrzn** [comment]
Hi, I think this might be due to your DF not having evenly spaced timestamps - see for instance the difference between the last time stamp and the one before is 30 minutes:
![image](https://user-images.githubusercontent.com/4806678/177768812-2beba38c-03be-4fec-9434-26fa561be01c.png)

You seem to have quite a few different time deltas in there:
![image](https://user-images.githubusercontent.com/4806678/177768923-cf6246c5-3146-48f5-a1c1-f3476dda6988.png)

Providing a data frame with hourly data would probably help and I hope solve the issue.

**Comment by hrzn** [comment]
Closing for now. Pls re-open if needed @colin99d
