### ISSUE TITLE
[BUG]Neural Network Models Throwing ValueError: The actual series must be strictly positive to compute the MAPE.

### ISSUE THREAD

**Issue by colin99d** [unit8co/darts#1063]
**Describe the bug**
Using neural network models throws the error: ValueError: The actual series must be strictly positive to compute the MAPE.
<img width="1027" alt="Screen Shot 2022-07-07 at 3 26 44 PM" src="https://user-images.githubusercontent.com/72827203/177856303-3a28bc2a-2511-4497-b5d5-f664e7fa9ad7.png">

**To Reproduce**
Steps to reproduce the behavior, preferably code snippet.

Use the data below:
[darren.csv](https://github.com/unit8co/darts/files/9066799/darren.csv)

**Expected behavior**

**System (please complete the following information):**
 - Python version: 3.9.13
 - darts version: 0.2.0

**Additional context**
Assuming that this is from the high volatility with the sudden spike in the data. Would there be a way to tell the model that the values cannot go below 0?

**Comment by colin99d** [comment]
I am trying to reproduce the error in google colab so you do not have to dig through our terminal to debug. However, I can confirm none of the actual values are 0 or below, since its all stock closing prices.

**Comment by sbabo-mattia** [comment]
Hello, I am having the same issue with version 0.20.0. Reverted back to version 0.19.0 and it seems like it is gone, the time serie has always been the same.

**Comment by martinb-bb** [comment]
Hello @hrzn  I can reproduce. I will send you an email with a notebook + data. Thanks 😄

**Comment by hrzn** [comment]
Hi, I have reproduced your issue and basically it's due to the use of a scaler built as `Scaler()`. [By default](https://unit8co.github.io/darts/generated_api/darts.dataprocessing.transformers.scaler.html) this builds a `MinMaxScaler(feature_range=(0, 1))`, so the smallest value in the actual series is 0, which causes the MAPE to complain. Note that it's anyway to a good idea to use the MAPE with such a scaler, as the scaling impacts the MAPE. You can for instance use a `MaxAbsScaler` instead: 

```python
from sklearn.preprocessing import MaxAbsScaler

scaler = Scaler(scaler=MaxAbsScaler())
```

**Comment by martinb-bb** [comment]
Awesome. Confirmed this works :) Thank you @hrzn !

**Comment by hansk0812** [comment]
I found that adding a small number does what you want as well without changing the scaler. 
```
MAPE(x + 1e-17, y + 1e-17)
```
