### ISSUE TITLE
Export model to ONNX

### ISSUE THREAD

**Issue by TamerAbdelmigid** [unit8co/darts#1071]
**Is your feature request related to a current problem? Please describe.**
A way to export the model trained in DARTS to other environment would be much appreciated.

**Describe proposed solution**
Ability to export model to [Open Neural Network Exchang](https://onnx.ai/) format, which is supported in [SKlearn](https://onnx.ai/sklearn-onnx/) and [Pytorch lighting](https://tugot17.github.io/data-science-blog/onnx/tutorial/2020/09/21/Exporting-lightning-model-to-onnx.html).

**Comment by TamerAbdelmigid** [comment]
Thanks @hrzn. I am trying to implement the models developed in DARTS into MATLAB, I'll try the interface between python/MATLAB, but it would be great if I could import my model directly into my MATLAB workflow, and reduce the overhead. Additionally, the final goal is to implement the model developed in DARTS in an embedded system, along those developed in MATLAB.

**Comment by hrzn** [comment]
OK, I see, thanks. I think that'd take more efforts, because getting a prediction with a Darts model involves usually quite a lot of non-trivial logic which is present in the Darts library only. I don't think that could easily fit within the ONNX protocol unfortunately. Maybe if one day there's a strong support for time series forecasting we could adapt to it.

**Comment by TamerAbdelmigid** [comment]
Thanks a lot, for all your effort in such an amazing library, and hopefully one day this can be implemented.
