### ISSUE TITLE
Grid Search ::: Pass past_covariates to NBEATSMODEL

### ISSUE THREAD

**Issue by OmarHory** [unit8co/darts#1097]
**Is your feature request related to a current problem? Please describe.**
I am trying to use Past Covariates into the NBEATSMODEL GridSearch.

**Describe proposed solution**
Add past covariates to the gridsearch as future covariates exist.

**Additional context**
darts == 0.20.0

![image](https://user-images.githubusercontent.com/43903002/180816624-220e775a-c761-4019-ba9c-9e58a6dcb592.png)

**Comment by dennisbader** [comment]
Gridsearch supports past covariates. Could it be that you have a key called "past_covariates" in you `params` dict?

**Comment by OmarHory** [comment]
![image](https://user-images.githubusercontent.com/43903002/180947653-06b6461d-2515-45e7-b30c-5f5d7f48a558.png)

I unfortunately only see **future_covariates** in the grid search params.
I also tried to pass the **past_covariates** in the params dict with no hope.

**Comment by OmarHory** [comment]
Thank you so much!
The problem is solved.

I have a quick question, why can't we do grid search on multiple time series?  
I tried to pass in a list of Time Series for both the **series** and **past_covariates**, apparently it must be a Time Series Object.

**Comment by dennisbader** [comment]
Currently gridsearch only supports single target `series` (and single past/future covariates). 
This is because Darts has `LocalForecastingModels` which only support single series and `GlobalForecastingModels` which support multiple series. Extending gridsearch to multiple series is in our backlog.

In the meantime you could checkout the `optuna` package (see [here](https://optuna.readthedocs.io/en/stable/index.html)) to implement your own hyperparameter tuning algorithm.

**Comment by OmarHory** [comment]
Thank you so much!
