### ISSUE TITLE
Good documentation on default scaling behavior

### ISSUE THREAD

**Issue by hrzn** [unit8co/darts#1166]

**Comment by adamkells** [comment]
Hi @hrzn  , seems like I might have been too ambitious with the Window transformations as a first issue! Have significantly more time to contribute now, so was thinking of doing some documentation work unless you have a better suggestion for an issue to work on?

**Comment by hrzn** [comment]
Hi @adamkells, sorry for my late reply! Yes, more & better documentation is always better :)

For this particular story, we had in mind of improving the docstring of `Scaler`, to explicit that the default sklearn scaler used under the hood may change e.g. MAPE error values, and point to other options that do not (e.g., MaxAbsScaler).

But in general adding more examples to docstrings a bit everywhere throughout the library, or complementing missing sections of the user guide, is always welcome 👍

**Comment by madtoinou** [comment]
Closing this issue, the docstring of `Scaler` clearly indicate which sklearn scaler is used by default since #720 and the impact of the scaler on the metrics is implicit but sufficiently intuitive since the values of the series are directly modified.

Also, a lot of example/code snippets has been added by #1956.
