### ISSUE TITLE
Unable to do prediction with past covariates with regression model

### ISSUE THREAD

**Issue by pdubey2018** [unit8co/darts#1192]
Hi All, I am building global regression model for a multiple products. I am new to Darts, and to time series. I am trying to understand Darts concept and code snippet to see if it can make my life easy. 

The goal is try to multiple models and multiple covariates to check. Then evaluate my model by 1. Historically testing, 2. Predicting a test series. I am getting errors and could not answers why I am getting this error and how to solve them.

```
# Future forecast days
HORIZON = 30

# List of time series of all group1 ( around 1000 time series)
y_all_series = TimeSeries.from_group_dataframe(df, group_cols=['group1'], time_col='date', value_cols='sale', freq='d')

# Divides training and test series
train_series = [series[:-HORIZON] for series in y_all_series]
test_series = [series[-HORIZON:] for series in y_all_series]

# past covariates - time series
past_covariates = TimeSeries.from_group_dataframe(df, group_cols=['item_cd'], time_col='date', value_cols=['price'], freq='d')
train_series_past_coveriate = [series[:-HORIZON] for series in past_covariates]
test_series_past_coveriate = [series[-HORIZON:] for series in past_covariates]

model = LinearRegressionModel(lags = [-1,-7], lags_past_covariates = [-1, -7, -10])

model.fit(train_series, past_covariates=train_series_past_coveriate)

preds = model.predict(n= HORIZON, series=test_series, past_covariates=test_series_past_coveriate)

```
I tried different HORIZON values still the same error.

`
2022-09-07 01:34:29 main_logger ERROR: ValueError: The corresponding past_covariate of the series at index 0 isn't sufficiently long. Given horizon `n=30`, `min(lags_past_covariates)=-10`, `max(lags_past_covariates)=-1` and `output_chunk_length=1`
the past_covariate has to range from 2022-08-24 00:00:00 until 2022-10-01 00:00:00 (inclusive), but it ranges only from 2022-08-04 00:00:00 until 2022-09-02 00:00:00.
`

It would be nice to have some help from you:
1. Help me identify how to fix the error. Basically seems incompatibility with HORIZON ( future dates) and the test dates
2. Efficiently get metrics for list of time series, instead of using looping over each prediction time series and training time series.
3. Is historical forecasting is incompatible with multiple time series? Is there any way to feed my entire training data ( with list of all time series) and instead of historical testing with individual series.
4. What is recommended way to evaluate such models ( is single split like below) or there is mechanism to do time series cross validation system ( expanding windows of training set)- could not find such splits in the documentation
5. Should I be using `input_chunk_length` and `output_chunk_length` to avoid the error above.

Sorry for long list of questions, I find the library very promising for me, but there is loads of informations , bit overwhelming (for time series new bee). Love to contribute to documentations either by providing a notebook or medium blog, to help others about my learnings. 

Thank you for your time

**Comment by hrzn** [comment]
Hi,
1. By default, the model will use `output_chunk_length=1`, meaning it's producing forecasts auto-regressively, and needs to consume past covariates as it goes. When you predict for a horizon `n=30`, the model needs to access the past covariates at lags `-1`, `-7` and `-10`. So it needs to access past covariates at position 29 (i.e., in the future). You can either pass `past_covariates` instead of `train_series_past_covariates` to `fit()` and `predict()`, but that will assume your past covariates are known up to 29 steps in the future. Otherwise you can build a model to forecast 30 steps in the future in one go by specifying `output_chunk_length=30`.
2. Most of the metrics in `darts.metrics` will work on multiple TimeSeries and parallelize computation.
3. Not at the moment
4. You can ask the models to bulk-predict on multiple TimeSeries, and then bulk-compare this to multiple validation TimeSeries (using e.g. `darts.metrics`). Otherwise for full backtesting the best way to go is to use `backtest()` or `historical_forecasts()` on isolated series.
5. You'll likely need `output_chunk_length > 1` yes. `input_chunk_length` is not defined for RegressionModels (it's determined by the lags you specify when building the model).

It'd be awesome if you want to write a blog post or help us improve the docs :)
