### ISSUE TITLE
Add MSTL method to `extract_trend_and_seasonality`

### ISSUE THREAD

**Issue by connesy** [unit8co/darts#1249]
When working with time series with multiple seasonalities it would be great to be able to decompose it using [statsmodels.tsa.seasonal.MSTL](https://www.statsmodels.org/dev/generated/statsmodels.tsa.seasonal.MSTL.html?highlight=mstl#statsmodels.tsa.seasonal.MSTL) by passing in a list of `freq` to `extract_trend_and_seasonality` and getting the trend and each seasonal component out.

**Comment by hrzn** [comment]
This sounds like a good idea. Would you be willing to contribute such an improvement?

**Comment by connesy** [comment]
I'm willing to give it a try. Would it be best to add it as an option, and tweak the output of `STL` to include multiple seasonal components, or make it a separate function?

**Comment by hrzn** [comment]
Sorry for my late reply @connesy. I would say the best is probably to add it as an option to `extract_trend_and_seasonality` and tweak the output based on this option.

**Comment by alexcolpitts96** [comment]
I was looking to use MSTL and was going to make a PR before I found this. I have written the code but haven't made a PR since statsmodels.tsa.seasonal.MSTL is currently in the development branch (stable is 0.13.5, dev is 0.14.0).

I couldn't find a date for statsmodel==0.14.0 being released. What are your thoughts around handling this?

**Comment by alexcolpitts96** [comment]
I broke my pull request. I will fix it and then it should be able to get merged soon-ish.

**Comment by madtoinou** [comment]
Solved by #1879.
