### ISSUE TITLE
handle predict kwargs in `historical_forecasts()` and `backtest()`

### ISSUE THREAD

**Issue by hrzn** [unit8co/darts#1294]

**Comment by RayDanks** [comment]
Hi, is this still outstanding with no assignee ? If so I'd like to take it as my first issue. I've already had a look through and familiarised myself with this particular issue, but will describe a bit more here once confirmed to be sure on my approach since it's my first contrib to this repo. Thanks :)

**Comment by hrzn** [comment]
Hi @RayDanks and sorry for the late answer!
I think this should constitute a fairly good first issue to work on. Basically we need to accept `predict_kwargs` arguments in `historical_forecasts()` and `backtest()` and propagate them all the way to the calls to `predict()`.

**Comment by madtoinou** [comment]
Implemented in  #2050.
