### ISSUE TITLE
Pass column names to LGBMModel to enable feature importance analysis

### ISSUE THREAD

**Issue by tuomijal** [unit8co/darts#1309]
First of all, thank you @hrzn and others for beautifully designed software! Bravo!

I wonder if it would be possible to pass feature names to `LGBMModel` in training phase? In case of LightGBM, that's pretty much everything needed for `explainability` as outlined in #675.

**Comment by dennisbader** [comment]
Hi @tuomijal and thanks for writing.

This is indeed a point that we have to think about for all the models for better interpretability and explainability.

- for LocalForecastingModels simple feature names are sufficient
- for RegressionModels (such as LightGBM) we need lagged feature names. For example: "pc_lag_-12", "fc_lag_10", "tg_lag_-1" (past/future covariates lags, and target legs)
- for TorchForecastingModels the simple feature names could be enough or something that acts on the model specific explainabity.

@hrzn, what's your opinion on that?

Internally, the models should still remain feature name agnostic as users can pass multiple time series with different component names (only the order matters).

**Comment by hrzn** [comment]
I agree. We should also align with what has been started by @dumjax in the ShapExplainer.

**Comment by kurteulau** [comment]
@dennisbader First, shout out to you and the Darts team since Darts is amazing. I really mean it! Since this task is still open, I wanted to ask if there was a temporary work around to get feature importances for LightGBMModel like there is for TFT as posted by @MagMueller in [#675](https://github.com/unit8co/darts/issues/675). Cheers!
