### ISSUE TITLE
Hierarchical Reconciliation for multiple series instead of multivariate series

### ISSUE THREAD

**Issue by wregter** [unit8co/darts#1316]
**Is your feature request related to a current problem? Please describe.**
I would like to use a global forecasting approach to forecast multiple store/product sales combinations and reconcile the forecasts afterwards. However, hierarchical reconciliation is only available for reconciling based on components, or multivariate series. I tried to transform my data to a wide format with each store/product combination representing a component like in [this example](https://unit8co.github.io/darts/examples/16-hierarchical-reconciliation.html) and reconciliation works. However, now my LGBM model is creating separate models for each sport/product combination it seems, as when I inspect the model object I see multiple fitted models. If there is a solution to this that I am currently not seeing then please let me know.

**Describe proposed solution**
Adding a hierarchical reconciliation approach based on multiple series.

**Describe potential alternatives**
Perhaps I could try to first keep the series as multiple series and perform the global forecast. Afterwards, I could transform the data to multivariate series (multiple components) and perform hierarchical reconciliation. However, this approach would be inefficient.

**Comment by dennisbader** [comment]
Hi @wregter, you are right, it's currently not possible to reconcile over multiple time series.
The hierarchy is embedded in a single target series, and it is only aware of its own components (the columns).

It is also true that when you convert your data into a wide format (multivariate time series), LGBM uses one model instance per component.

For now, your potential alternative is the only way to make hierarchical reconciliation work with a single global LGBM model.

@hrzn, what do you think about multi series reconciliation?

**Comment by hrzn** [comment]
I'm not sure that I fully understand the issue.

We decided to perform reconciliation within components of a single time series for the following reason:
* To perform reconciliation, the different series being reconciled must share the same time axis, which will be naturally enforced if these reconciled series happen to be the components of a multivariate series.
* Reconciliation is always (AFAIK) performed over univariate series. If we were to allow reconciling over multiple series, we would have to check they all are univariate.
* Having reconciliation done over single multivariate series (rather than multiple univariate series) allows us to neatly store the hierarchy as part of the series itself (which could be useful for some future models to also consume the hierarchy itself to improve the forecasts 🤯  - we don't have yet a model like this in Darts but some exist in the literature).

Now, three things can happen as I see it:
* Option 1: You can have multiple models predicting your different univariate time series, in which case you'll simply have to `concatenate()` the resulting series into one multivariate series, as shown in the example.
* Option 2: You can have a single global univariate model and use it to predict your different univariate time series. Here' too you'll have to `concatenate()`.
* Option 3: You can have a single multivariate model predicting all univariate components at once (and producing multivariate series in output), in which case you're ready to go (as done initially in the example notebook). 

With LGBM, the underlying LGBM regressors are not vector-valued anyway so multiple regressors will be used for each of the dimensions in Option 3. Option 1 will also use multiple LGBM regressors as it builds a separate model per component. Option 2 will only build one underlying LGBM regressor.
Note that with other models this could be different. E.g. deep learning models would build only one model in option 3 and predict all dimensions at once.

I hope this helps.

**Comment by wregter** [comment]
Thank you both for your replies! @hrzn @dennisbader 

I now understand the reasons why performing reconciliation over multiple time series is not ideal. I will try your suggestions, thanks!
