### ISSUE TITLE
No matching distribution found for torch>=1.4.0 (from u8darts)

### ISSUE THREAD

**Issue by ncdingari** [unit8co/darts#133]
When I use `pip install u8darts`

 - Python version: 3.7.1

**Comment by hrzn** [comment]
Hello, that looks like an issue with your pip setup. Can you do `pip install torch` to test?
In addition, we have seen issues with Python 3.7.1. I would recommend using a more recent version like 3.7.7.

**Comment by flobrec** [comment]
I had the same issue. What worked for me was:

- Installed Pyhton 3.7.7 (as recommended, put probably not the issue)
- installed torch with `conda install pytorch torchvision cpuonly -c pytorch` (according to [https://github.com/pytorch/pytorch/issues/29395#issuecomment-551214139], `pip install torch` is not working on Windows, hence went to [https://pytorch.org/], see Quick Start Locally)
- tried to install u8darts but had an issue with fbprohet and cython version, downgraded with `conda install cython=0.29.17` (probably this step can be skipped since I still had an issue with fbprophet afterwards
- tried to install u8darts but had an issue with fbprophet, therefore first installed fbprophet with `conda install -c conda-forge fbprophet`
- installed u8darts with `pip install u8darts`
- after that, still had to install plotly, but then the darts-intro.ipynb from the examples ran through

**Comment by TheMP** [comment]
Hi @flobrec, thank you for letting us know. We have addressed your issue and merged it to develop branch. It will come out together with release 0.3.0 of Darts.

**Comment by TheMP** [comment]
Hi @flobrec, I'm happy to announce that the issue you have reported is resolved now.
