### ISSUE TITLE
How to get metrics after predictions while using from_group_dataframe?[BUG]

### ISSUE THREAD

**Issue by sputta01** [unit8co/darts#1369]
**Describe the bug**
How to get metrics after predictions while using from_group_dataframe? I don't see any page / resource to do this. 

**To Reproduce**
Here is the code I'm using. 
```
test_data = data_transf.groupby('material').tail(100)
train_data = pd.concat([data_transf, test_data]).drop_duplicates(keep=False)
train_dartsdf = TimeSeries.from_group_dataframe(train_data, 
                                       group_cols = ['material'], 
                                       time_col = 'weekendingdate', 
                                       value_cols = ['units'])
test_dartsdf = TimeSeries.from_group_dataframe(test_data, 
                                       group_cols = ['material'], 
                                       time_col = 'weekendingdate', 
                                       value_cols = ['units'])
model = RegressionModel(lags = [-1], model = LinearRegression())
model.fit(train_dartsdf)
test_truth = TimeSeries.from_values(test_data.units.values)
test_predictions = model.predict(n = 100, series = test_dartsdf)
print(mape(test_predictions, test_truth))
ValueError: The two TimeSeries sequences must have the same length.
```

**Expected behavior**
A numeric value of metric 

**System (please complete the following information):**
 - Python version - 3.9.12
 - darts version - 0.22.0

**Additional context**
Here is the vector length. 
len(test_truth), len(test_predictions), len(test_dartsdf))
(1080000, 10800, 10800)

**Comment by madtoinou** [comment]
Hi!

Your data preparation steps are a bit counter-intuitive: instead of using `drop_duplicates(keep=False)` to generate a train and test splits, I would recommend using `TimeSeries` objects directly:
```
# one single TimeSeries contain all the data
ts_dartsdf = TimeSeries.from_group_dataframe(data_transf, 
                                       group_cols = ['material'], 
                                       time_col = 'weekendingdate', 
                                       value_cols = ['units'])
# using slicing operator, test_dartsdf contains the last 100 samples
train_dartsdf, test_dartsdf = ts_darsdf[:-100], ts_darsdf[-100:]
```

Note that these slicing operations could have been using on the `DataFrame` objects as well, in a similar manner:

```
train_dartsdf = data_transf[:-100]
test_dartsdf = data_transf[-100:]
```

Finally, the error message is expected since the length of the `TimeSeries` you're reporting are not matching: `len(test_truth)=1080000` and `len(test_predictions)=10800`, potentially because of code not shared in your post. You could predict and obtain the metric between the forecasted values and the ground_truth by simply calling:

```
test_predictions = model.predict(n = len(test_dartsdf))
print(mape(test_predictions, test_dartsdf))
```

I hope that my explanations and code snippets will help you use Darts>
