### ISSUE TITLE
Questions about input data dimensions

### ISSUE THREAD

**Issue by Luffffffy** [unit8co/darts#1387]
In my time series data，i have a dataset of  about 100 multivariates in 3 years with the dimension of days
I built my dataset like the pytorch lstm model (eg: (sequence length, batch size,  input size) 
I tried (30, 128, 100), It means that I build the data of the past 30 days to predict the future

My questions is： 
1, in Darts, how to build the data set format of 3D time series，Instead of a dataframe like AirPassengers.csv
2, If not, how can i predict future N days based on historical data at a time using dart

thanks!!!

**Comment by madtoinou** [comment]
Hi!

Darts' `TimeSeries`come with several constructors, including `.from_series` and `from_values`, relying respectively on `pandas.Series` and `numpy.array`. If you don't have a time range/axis ready, you will want to use `from_times_and_values'. They support 3D times-series (called multivariate in darts).

As for the batch and lookback (called `input_chunk_length` in darts) size, the simplest would be to use the model constructor and/or `historical_forecast`parameters to control them. You might want to check the  function `historical_forecast` available for all the models, otherwise `predict` will probably be enough if you just want to forecast `n` values.

There are several [tutorials/example](https://unit8co.github.io/darts/examples.html) in the documentation, don't hesitate to look them up!
