### ISSUE TITLE
Custom business day

### ISSUE THREAD

**Issue by BlonskiP** [unit8co/darts#1420]
Hi! 

Lately I'm learning to use darts for prediction of activities during business days. 
Timeseries has frequency which have to be satisfied (day etc.) 
My data is not collected during Saturdays only, so right now I'm filling saturndays with zeros, also there will be no predictions for Saturdays.
I just wonder if its a good way or if it should be diffrent.

**Comment by dennisbader** [comment]
Hi @BlonskiP. Yes, you can use CustomBusinessDay frequency for that. Below is an example:

```
import pandas as pd

from darts import TimeSeries


# make a custom businessday frequency
freq = pd.offsets.CustomBusinessDay(weekmask="Mon Tue Wed Thu Fri Sun")

# generate a dataframe
idx = pd.date_range(
    start="11-28-2022",
    end="12-25-2022",
    freq=freq
)
df = pd.DataFrame({"a": [i for i in range(len(idx))]}, index=idx)

# pass the frequency to time series creation
ts = TimeSeries.from_dataframe(
    df,
    freq=freq
)
```

**Comment by BlonskiP** [comment]
Thanks, I will try it out soon ;)

**Comment by hrzn** [comment]
On another note: In general I really don't recommend fixing frequency issues by filling with placeholder values (e.g. 0). This is because the models would pick this up believing those are actual values that need to be modelled too. This is not the same if you have actually zero of something of course.
