### ISSUE TITLE
NBeats does not work for long-term daily time series data. 

### ISSUE THREAD

**Issue by whoopydev** [unit8co/darts#1442]
Hey guys, 

I am following the code as per this notebook: https://www.kaggle.com/code/stpeteishii/google-stock-prediction-darts/notebook

It's a really simple implementation of the NBeats model, and it takes into account 400 days of the Google stockprice. However, when I increase the train and val parameters to take into account all 4000 days, the N-Beats forecast is completely thrown of and gives a completely incorrect forecast with a mape of over 100. 

I understand that one possibility is due to the seasonal nature of the stockprice. I tried the Dicky Fueller test (not using the Darts library) and it is indeed seasonal data. However, when I try to inspect seasonality with the Darts library as follows: 
```
from darts.utils.statistics import plot_acf, check_seasonality

plot_acf(train, m=365, alpha=0.05)
```
I get a max lag error. 

Can someone please help me as to how to forecast stock market data of a 10 year daily timeseries using the darts library? Also, I'd be extremely grateful if someone could give me some additional tips when it comes to forecasting stock data with darts since there's not much info/tutorials available online. 

I've gone through the entire docs and I've got a good hang of working with darts using the darts open-source databases, however none of the examples seem to work with stock market data. 

Any help would be greatly appreciated. 
Thanks!

**Comment by hrzn** [comment]
Hi, there's nothing special about stock data in terms of how to use Darts. For your particular problem, it might be due to too large an `input_chunk_length`, which perhaps prevents the model from being trained on enough samples.

Now, that being said, please bear in mind that you should not expect any kind of good performance when fitting models on stock prices history to forecast their future :) I'm not surprise that even a well trained/validated model would obtain terrible performance on a proper test set. I also highly doubt that there is any seasonality in stock prices (if there were, it would immediately be arbitraged and removed).
