### ISSUE TITLE
Quantiles without Sampling  

### ISSUE THREAD

**Issue by FunkyFabe** [unit8co/darts#1445]
**Problem:**
Calculating the quantiles of a probabilistic forecast requires sampling.
When working with parameterised likelihood models such das the gaussian likelihood, one must use the num_samples parameter in the predict method to obtain samples. Then one can calculate the quantiles from the probabilistic time series.
In case of parameterised likelihood models one could directly calculate the the quantiles and avoid da calculation for sampling.
What is the advantage of sampling? 

**Proposed Solution:**
Extend the predict API to calculate quantiles using the internal estimated parameters of the distribution.

**Alternative Solution:**
Make raw outputs of the neural network accessible.

**Comment by hrzn** [comment]
Storing samples allows TimeSeries to be completely distribution-agnostic and work for any kind of distribution, parametric or not. Furthermore, storing parameters (e.g. of a Gaussian) would not scale as soon as the dimension becomes large (in time and/or number of components), due to the covariance matrix requiring O(N^2) parameters. Finally, samples usually incur only a very small performance penalty (their computation is vectorized), and no significant loss of accuracy for a distribution like the Gaussian.

**Comment by TueLindhart** [comment]
In my use case, I specifically need to predict exact quantiles. When I use sampling I also gain obviously wrong quantiles where the quantiles are drifting to values that are obviously wrong. I tried to use three models where I used 0.14, 0.5 and 0.86 quantiles. However, I was not allowed to do this either. I think you should seriously consider to allow gaining the raw quantiles. Otherwise, you should at least make sampling work properly.
