### ISSUE TITLE
[BUG] TimeSeries.from_group_dataframe without time_col but with pd.RangeIndex fails

### ISSUE THREAD

**Issue by 2-5** [unit8co/darts#1491]
**Describe the bug**
`TimeSeries.from_group_dataframe` fails when called without specifying `time_col`, even if the dataframe has a `pd.RangeIndex` as documented.

**To Reproduce**

```python
import pandas as pd

from darts import TimeSeries

data = {
    "a": [5, 6, 7, 8],
    "b": [9, 9, 0, 0],
}
df = pd.DataFrame(data=data)

print(df)
print()
print(df.index)
print()

ts = TimeSeries.from_group_dataframe(df, "a")
print(ts)
```

**System (please complete the following information):**
 - Python version: 3.10
 - darts version 0.23.1

**Additional context**

```python
   a  b
0  5  9
1  6  9
2  7  0
3  8  0

RangeIndex(start=0, stop=4, step=1)

ValueError: If time_col is not specified, the DataFrame must be indexed either with a DatetimeIndex, or with a RangeIndex.
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    ts = TimeSeries.from_group_dataframe(df, "a")
  File ".venv\lib\site-packages\darts\timeseries.py", line 802, in from_group_dataframe
    return [
  File ".venv\lib\site-packages\darts\timeseries.py", line 803, in <listcomp>
    TimeSeries.from_dataframe(
  File ".venv\lib\site-packages\darts\timeseries.py", line 656, in from_dataframe
    raise_if_not(
  File ".venv\lib\site-packages\darts\logging.py", line 78, in raise_if_not
    raise ValueError(message)
ValueError: If time_col is not specified, the DataFrame must be indexed either with a DatetimeIndex, or with a RangeIndex.
```

**Comment by madtoinou** [comment]
Hi!

Thank you for reporting the bug, it seems to be caused by the output of `pd.groupby()` that replaces the `RangeIndex` of the original `DataFrame` by a `Int64Index` (which is deprecated since pandas 1.4.0).

The three solutions I can think of are:
- remove support for RangeIndex if the `time_col` is not provided, forcing the user to create a DatetimeIndex prior to calling `from_group_dataframe`. Even by doing so, the user will probably have to provide the `freq` argument to avoid a `ValueError` about "missing freq that could not be inferred" (unless the observations in each group follow a pattern)
- call `reset_index` to convert the index of the group back into a `RangeIndex` (but the "distance/gap" between the observations will be lost, probably making this TimeSeries meaningless)
- try to convert the Int64Index into a RangeIndex after inferring its frequency (would preserve the data), if no frequency can be inferred, create a RangeIndex of step 1 between the min and the max of the Int64Index and fill the gaps with `NaN` (making the `TimeSeries` incompatible with several models).

I think that my favorite option is the last, eventually raising a warning for each group for which the frequency of the index could not be inferred. Curious to know the opinion of others before diving in the implementation.

**Comment by 2-5** [comment]
Originally my data had a `DatetimeIndex`, but one irregularly sampled, with no fixed frequency. Since darts doesn't support that and requires a frequency, I removed the `DatetimeIndex` and replaced it with a `RangeIndex` and encountered this bug.

Why does darts insist on timestamps having a frequency? My understanding is that many models (lagged Catboost, ...) don't use the time component at all.

If darts forces a `DatetimeIndex` with frequency to be used, I will probably just remove the original times and just create fake timestamps at regular intervals. It seems to me that the insistence of regular timestamps is forcing users into all kinds of workarounds. I would suggest relaxing this requirement, replacing it with warnings, and maybe throw an exception when a situation is encountered (like some metric) where equally spaced timestamps are absolutely required.

**Comment by madtoinou** [comment]
@hrzn correct me if I am wrong but from my understanding, series must have a fixed frequency (either in their `RangeIndex` or `DatetimeIndex`) so that models that are using lags (not necessarily time component per say) won't be able to compute them properly?

The `resample()` method can used enforce a fixed frequency to a series, but it will probably not work on your data considering the fact that you are using the factory method `from_group_dataframe` directly. You will have to create fake ranges of Timestamps for each group, which might be a bit annoying.

**Comment by 2-5** [comment]
But there are use cases where you don't actually want equally spaced timestamps.

For example in financial markets forecasting, using so called "volume based time" instead of "wall time" is quite wide-spread. Meaning that you have 1 time tick every "$1m traded", not every "5 minutes" (https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2034858)

So if I input 5 consecutive rows, with irregular timing between them, I expect these exact 5 rows to be the lagged values, and I don't expect darts interpolating (inserting) new ones in between which would ruin the statistics.

I understand that this is maybe a specialized use case and not what the most common usage is, but from reading the darts documentation I didn't realize that darts tries to resample "lagged features" to a common frequency.

Maybe a documentation page could be added detailing exactly what darts expects in terms of timestamp frequency, why, and how they are used, and in particular how are features interpolated/lagged.

**Comment by madtoinou** [comment]
Oh but for this kind of data, you should be able to use `RangeIndex` without any problem and the step would be equal to 1 (corresponding to the "$1m traded" tick). You would however have to create the TimeSeries one by one instead of using the `from_group_dataframe`.

I will draft a PR so that `from_group_dataframe()` is able to create a list of `TimeSeries` from the kind of DataFrame that you described in your first post, and give the possibility to either "fill the holes" (to preserve the distance/time between the observations) or "squeeze the index" (to support the "volume based time" kind of series).

In the context of financial market forecasting (assuming that it's the kind of data that you were using when you found the bug), which kind of features would you use to group de samples into TimeSeries? I just want to make sure that it actually make sense to reset the index for this kind of use case or if I misunderstood something.

**Comment by 2-5** [comment]
> Oh but for this kind of data, you should be able to use RangeIndex without any problem and the step would

Right, that's exactly what I did, I replaced the `DatetimeIndex` with `RangeIndex`. But it's a bit weird, and it introduces the possibility of user-errors, if you join `TimeSeries` with shifted `RangeIndex` origin. If the original timestamps were kept, there would be no possibility of error.

Because of this bug, I did the grouping manually instead of using `from_group_dataframe`, so there is no particular impact to me, but it's a nice functionality.

> which kind of features would you use to group de samples into TimeSeries

My use case is more complicated, but a few common examples to consider:

- separate TimeSeries for each stock ticker:
```
          ****
11:01:02  MSFT  100
11:01:03  AAPL  212
11:01:14  MSFT  101
```

- separate TimeSeries for each stock ticker & trading venue:
```
          ****  ****
11:01:02  MSFT  ARCA  100
11:01:03  MSFT  NYSE  102
11:01:14  MSFT  ARCA  101
```

- group by certain categorical property, in this case `0/1/2`, because each partition has different statistics (for example - 0-regular, 1-news-event, 2-after-hours):
```
                      *
11:01:02  MSFT  100   0
15:30:03  MSFT  101   1
16:01:14  MSFT  102   2
```

In all the example above the pattern is the same: you load a combined/mingled DataFrame and you extract the actual per-entity/per-aspect TimeSeries.

**Comment by dennisbader** [comment]
I'm working on something which allows a properly indexed integer index (index with costant steps but not necessarily in order) to be accepted by TimeSeries.from_dataframe().

pd.groupby() results in an Int64Index, even if the original index is a RangeIndex. This is the reason why `TimeSeries.from_group_dataframe()` fails.

**Comment by hrzn** [comment]
@2-5 the requirements on the time steps are required to make time series models work.
On actual time-indexed data, we need a well defined freq in order for instance to be able to generate the future dates of the forecasts. All forecasting models make the underlying assumption that the freq is constant. Note that this doesn't mean that the time delta between two timesteps is constant (eg. business-day frequency can be valid).

If you have data that is not indexed by datetimes but where the sampling is triggered by something else (e.g. some value crossing $1m steps), then in the context of time series modelling it anyway does not make sense to use datetime-indexed time series (even if timestamps are recorded for events). This is because time series models wouldn't be able to know the future timestamps of forecasted series. So to use forecasting models in your case, the best way is (I think) to go ahead and use a RangeIndex, where the ticks indicate the occurence counts of the $1m-crossing event. It also means that your forecasts will contain values that are indirectly assumed to happen at these future value-crossing-times.

The vast majority of time series modelling today is performed with fixed frequency assumptions, which is indirectly why Darts also has this requirement. Capturing processing happening at irregular times would fall more into point-process modelling, and there the models have to be different compared to forecasting (e.g. they have to also predict the future time stamps at which future events occur, which forecasting models don't do). It is possible that point processes will be supported in Darts at some point, at which point we may create a new data class to capture them properly.

**Comment by hrzn** [comment]
> In understand the theoretical aspects. In practice however people disregard all that and for example use tree models (lagged or not) and the timestamps are completely discarded. Which is why it's possible to use a RangeIndex in the first place. So it seemed to me that darts fell on the pragmatic (user-friendly) side of the debate (versus the purity one).

This is not only about purity, but also correctness :) Most forecasting models (tree-based or otherwise) may not look at the actual timestamps, but imagine we a series with the following irregular time steps:
```
ts  y
2000-01-01  1.1
2000-01-02  1.5
2000-01-06  1.2
2000-01-08  1.3
```

We train a model and ask it to forecast the next `n` timestamps. What should these timestamps be? Without a well-defined frequency, the whole problem is ill-defined, and the model will likely not be doing what's intended, even if it ignores the timestamps.

I think your example is also a symptom of that. You can brush away the problem temporarily by using some integer-based index, but then if the actual timestamps of your forecast matter (e.g. to join them with your test data - is it `510, 512` or `510, 511` ?) this is when the rubber hits the road. Modelling irregularly-spaced data requires models of a different nature.
