### ISSUE TITLE
Error using TimeSeries.from_group_dataframe for a dataframe containing multivariates (Various columns including the target variable)

### ISSUE THREAD

**Issue by SireeshLimbu** [unit8co/darts#1548]
I encountered the same issue as mentioned [here](https://github.com/unit8co/darts/issues/299), regarding past covariates and so I used TimeSeries.from_dataframe(df, time_col, value_cols) as @hrzn mentioned in that thread. I still get the same error 'The provided sequence of target series must have the same length as the provided sequence of covariate series'. Following is my simple LSTM 

```
# Where 'microbusiness_density' is the target
# df1 is the main dataframe after feature extraction and cleaning, it has 21 columns/covariates. All are 39 months long

X = df1.drop(['microbusiness_density'],axis = 1)
y =  df1[['microbusiness_density']]

from darts import TimeSeries
#df1.Index is of DataTime type 
cols = list(df1.drop(['microbusiness_density'],axis = 1).columns)
X = TimeSeries.from_group_dataframe(X,group_cols = cols ,freq = '1MS')
y = TimeSeries.from_dataframe(y,freq = '1MS',value_cols = 'microbusiness_density')

from darts.models import BlockRNNModel
from darts import concatenate

model = BlockRNNModel(input_chunk_length=38,model = 'LSTM',dropout=0.2,random_state = 42, output_chunk_length = 1)

#Error here
model.fit(y, past_covariates=X)
```

 - Python version:  3.7.12
 - darts version 0.23.1

**Comment by dennisbader** [comment]
Hey @SireeshLimbu .

There are two main points I want to clear.
- You get this error because `TimeSeries.from_group_dataframe()` returns a list of time series objects, and `TimeSeries.from_dataframe()` returns a time series object.
You have to supply either a list of series of the same length for each `series` (your `y`) and `past_covariates` (your `X`), or a single time series object for the two. 
- `TimeSeries.from_group_dataframe()` is supposed to extract a list of time series that represents the groups made from the unique values of your `group_cols` features. To me it seems you group by all the columns in your pandas DataFrame (excluding "microbusiness_density"). If you don't actually have multiple groups, then you could simply use:
```
X = TimeSeries.from_dataframe(
    df1,
    value_cols=list(df1.columns.drop("microbusiness_density")),
    freq="1MS"
)
```

**Comment by SireeshLimbu** [comment]
Hi @dennisbader,

      Thank you for your response! Right! I think it seems to work with your solution! Thanks! I was confused how to use 21 covariate columns in df1 (including target column) each of the same length 39 months!

I have two questions here:

1.  When you say If I don't have 'multiple groups', does that mean multiple covariate series? Because as I mentioned df1 dataframe[39,21] contains 21 columns/covariates (including target column 'microbusiness density') and 39 months/rows . I want to use these 20 columns/covariates (past-covariates)  each of 39 months to forecast the microbusiness density 3 months in the future (these 3months begin after the last month in df1, just to be clear). The way you mentioned above, Is it one way to achieve it?

2. Once I get the predict lets say I use model.predict(n=1, past_covariates = X). It gives me an array within a timeseries object. Maybe this is a very basic question, but how do I get/extract/convert this object of predicted month into a normal numpy float type?

Many thanks!

**Comment by dennisbader** [comment]
1. With groups i mean for example a store having different products for which they have historical sales. Now each product is one group. Since you only have one target series `y`, you have one group -> you don't have to use a list of target series.
Regarding the covariates: You can use any number of features as covariates (in `X`) to help improve forecasts of your target series `y`. Since `X` in your case has 20 columns, you will get a single multivariate (multi-component/feature) time series with `TimeSeries.from_dataframe()`. See [the documentation](https://unit8co.github.io/darts/generated_api/darts.timeseries.html#timeseries) of `TimeSeries` for more information about the definition of a time series.

2. You can do this with `TimeSeries` methods [`values()`](https://unit8co.github.io/darts/generated_api/darts.timeseries.html#darts.timeseries.TimeSeries.values), [`all_values()`](https://unit8co.github.io/darts/generated_api/darts.timeseries.html#darts.timeseries.TimeSeries.all_values), [`pd_dataframe()`](https://unit8co.github.io/darts/generated_api/darts.timeseries.html#darts.timeseries.TimeSeries.pd_dataframe), [`pd_series()`](https://unit8co.github.io/darts/generated_api/darts.timeseries.html#darts.timeseries.TimeSeries.pd_series). I.e.

```
preds = model.predict(n=1, past_covariates = X)
preds_arr = preds.all_values()
```

**Comment by SireeshLimbu** [comment]
Hi again,

       Great explanation. Its clear now! Thanks for the suggestions as well! I will close this topic now!
