### ISSUE TITLE
Understanding covariates with more details

### ISSUE THREAD

**Issue by LzyFischer** [unit8co/darts#1623]
Sorry that I have seen your documents of covariates, while I'm still wondering how do we implement training RNN with future covariates. do we just concatenate future covariates in next time step with multiple target variates in current time step in sample dim?

**Comment by dennisbader** [comment]
Hi @LzyFischer, [here](https://unit8co.github.io/darts/examples/08-DeepAR-examples.html) is an example that trains an RNNModel with future covariates.

In the covariates user guide [here](https://unit8co.github.io/darts/userguide/covariates.html#summary-tl-dr), it is shown how to train a model with past and/or future covariates in general:

The target and covariates series are always separated and Darts will extract the necessary input from your provided data.
Let us know if you have further questions.

**Comment by LzyFischer** [comment]
Thanks for your sincere reply. Moreover, I wonder (1) Why there is no past covariates in RNNModel, it seems that you just concatenate future covariates in step n+1 and target series in step n at sample dimension, why can't we concatenate past covariates and target series in step n? (2)for lstm, there could be output_chunk_length more than 1, but isn't it use the predicted values to predict furture values after the first horizons?

**Comment by madtoinou** [comment]
Hi @LzyFischer,

1. The `RNNModel` does not just concatenate the `future_covariates` at time `t+1` to the target at time `t` but relies on what Darts calls `dual covariates` ; both past ("historic") and future values of the `future_covariates` are used in order to generate the hidden states. Since the model is recurrent (and `output_chunk_length=1`), `past_covariates` would not make much sense as its future values would become necessary to predict anything with `n>1` (effectively matching the requirements of the future covariates).
2.`output_chunk_length=1` forces the `RNNModel` to properly use its hidden state (one per predicted value), and yes, if the forecast horizon `n` is greater than 1, the model will rely on its own outputs to predict the next steps. The `training_length` parameter allows however to mimic this scenario during training, to improve the quality of the hidden state.

Sorry for the wait, I hope that it clarifies things.

**Comment by juste97** [comment]
@dennisbader @madtoinou Sorry to comment on this closed issue. Just to further clarify, regarding some covariates, how does this not introduce leakage? In BlockRNN, I use, e.g., time variables as future covariates, and for past covariates, something like shifted statistical features of my target variable. So what context window is used for these (compared to how future covs are used in the regression type models)?

**Comment by madtoinou** [comment]
Hi @juste97,

I am not sure to understand your question, I am going to assume that it is about deep learning models in general : the "lags" (to make the analogy with the regression models) of these models for covariates is `input_chunk_length` for the `past_covariates` and `output_chunk_length` for the `future_covariates`. Similarly to the regression models, if `n>output_chunk_length`, the model will also access the future values of the `past_covariates` during the auto-regression.

Even if you use statistical features of the target variables as past covariates, as long as it don't rely on the timestamps being forecasted, there is no leakage.

Maybe I did not understand what you meant by leakage in this context?

**Comment by juste97** [comment]
@madtoinou Thanks for your reply! I was especially worried that this might inadvertently use information from the future beyond the current prediction point, thus introducing data leakage. I'm still not sure if I understand correctly, as the RNNModel does not have an output_chunk_length variable, but only input_chunk_length. But I suppose it does not use future values of the future covariates beyond prediction time?

**Comment by madtoinou** [comment]
`RNNModel` does have a `output_chunk_length` parameter but it's set to 1 and cannot be changed due to the nature of the model. If a future covariates series is provided, it will just be able to look at the value of the future covariates corresponding to the currently forecasted timestamp. Note that if at prediction time, `n>1`, the model will perform several forecasts/forward pass (auto-regression) and will access (iteratively) to several values of the covariates (but always one by one).
