### ISSUE TITLE
[BUG] after update group cols does not work

### ISSUE THREAD

**Issue by mahmoud1410** [unit8co/darts#1634]
**Describe the bug**
![image](https://user-images.githubusercontent.com/94221340/223778233-306c8dcb-4477-42ea-b4a2-abbd0d8033e1.png)
 the problem it wants to regard  group cols into which string into float

**Expected behavior**
it was running smoothly without erorrs
 - Python version: [e.g. 3.9]
 - darts version [0.23.1]

**Comment by mahmoud1410** [comment]
okay thanks a lot, it works now.
but I want to highlight before the updates it was much easier and representable.
thank you again

**Comment by dennisbader** [comment]
My guess is that in your previous darts version our RegressionModels did not yet use static covariates -> no error was raised as the data was not used.

Nowadays RegressionModels use static covariates which is why you get the error when using non-numeric data.

You can also use `StaticCovariatesTransformer` to encode the static covariates into numeric data, see [here](https://unit8co.github.io/darts/generated_api/darts.dataprocessing.transformers.static_covariates_transformer.html#darts.dataprocessing.transformers.static_covariates_transformer.StaticCovariatesTransformer).
