### ISSUE TITLE
[Question] History of model error/loss during training ?

### ISSUE THREAD

**Issue by simonweppe** [unit8co/darts#1644]
Hi there, and thanks for the great tool.

Is there a way to get the history of model error/loss during training ? 
For example to plot training curve and sanity check what happens during training. Something like this :

![Screenshot from 2023-03-12 23-58-24](https://user-images.githubusercontent.com/7277011/224579048-cdb5bbca-c9a3-45b5-a043-3402f2057bdc.png)

**Comment by madtoinou** [comment]
Hi,

Darts automatically save (thanks to `PyTorch Lightning`) training and validation metrics in the `darts_logs` folder in a format compatible with the `tensorboard` library by default.

You can simply install it using `pip install tensorboard` and run `tensorboard --logdir=darts_logs` in your terminal in order to access this visualization tool and track the progress of your model during its training.

If you don't want to use `tensorboard`, you can use the `logger` key of the `pl_trainer_kwargs` parameter of the model's constructor to define another callback and save the metrics in another format ([documentation](https://pytorch-lightning.readthedocs.io/en/stable/common/trainer.html#logger)).

**Comment by dennisbader** [comment]
There is also the option to write a custom callback for logging as explained here: https://github.com/unit8co/darts/issues/811
