### ISSUE TITLE
[BUG] Can't open m4, air pickled data sets

### ISSUE THREAD

**Issue by afogarty85** [unit8co/darts#1671]
When trying to follow the guide here: https://unit8co.github.io/darts/examples/14-transfer-learning.html

And when trying to run, for example

```
with open("m4_monthly_scaled.pkl", "rb") as f:
    m4_series = pickle.load(f)
```

if I examine `m4_series` (same with air) I get this error: `AttributeError: 'PandasIndex' object has no attribute 'dtype'`

**System (please complete the following information):**
 - Python version: 3.10
 - darts version: 0.23.1
 - pandas version: 1.5.3

**Comment by madtoinou** [comment]
Hi,
This tutorial was intended to be used with Python 3.9, darts 0.18.0 and xarray 0.1.8.2 (see the first cells in the Setup section). Some breaking changes has since been introduced, notably in the pickle library.

In order to load these datasets without using the custom functions defined in the notebook, you can use:
```python
from darts.datasets import AirPassengersDataset
air = AirPassengersDataset.load()
```

For the other two, you'll have to find them in a format that can easily be converted into `pd.DataFrame` and create ts using `TimeSeries.from_dataframe(...)` (m3 as csv [here](https://forvis.github.io/datasets/m3-data/), m4 [there](https://www.kaggle.com/datasets/yogesh94/m4-forecasting-competition-dataset))

Sorry for the inconvenience

**Comment by afogarty85** [comment]
Thank you!
