### ISSUE TITLE
Are encodings lagged in regression models?

### ISSUE THREAD

**Issue by hkogel** [unit8co/darts#1688]
Hi,
When I add an encoder in a regression model, it looks to me as if the respective encoding is also lagged according to the lags we specified when we instantiated the model. Is this the case?
I suppose that for many encodings we would usually only like to include the non-lagged version of it (e.g. positional encoding / day of week / month / etc.).

The example below illustrates this behavior:
- Instantiate a LinearRegressionModel with lags_past_covariates=2
- Add one encoder for past covariates
- Fit the model using a one-component past covariate called single_past_covariate

When printing the model coefficients, we can see that there are 4 coefficients. It looks to me as if this results from lag1 and lag2 for single_past_covariate and lag1 and lag2 for the position encoding.
```
import numpy as np
from darts.datasets import AirPassengersDataset
from darts import TimeSeries
from darts.models import LinearRegressionModel

np.random.seed(423)
series_air = AirPassengersDataset().load().astype(np.float32)
single_past_covariate = TimeSeries.from_times_and_values(
    series_air.time_index,
    np.random.sample(len(series_air))
)

lr = LinearRegressionModel(
    lags_past_covariates=2,
    add_encoders={'position': {'past': ['relative']}}
)

lr.fit(series=series_air, past_covariates= single_past_covariate)

print(lr.model.coef_)
[11.36563929  1.33528219  7.42132133  1.33528219]
```

I very much appreciate the work you all do.

Thanks,
Heinrich

**Comment by madtoinou** [comment]
Hi @hkogel , thank you for your interest in darts and this very detailed issue.

You are indeed correct, the features generated by the encoders are also lagged with respect to the values of lags passed to the model. In the case of your example; `['lag_-2_0', 'lag_-2_darts_enc_pc_pos_relative', 'lag_-1_0', 'lag_-1_darts_enc_pc_pos_relative']`. The only components of the input timeseries that are not lagged are the static covariates.

I however don't agree with the fact that some encodings should not be lagged: since each lag correspond to an entry (timestamp) in the "support" timeseries, each of these entries should have the same features. If not, you introduce some kind of asymmetry between the lags and mask some information.

I might however be wrong, @dennisbader WDYT?

**Comment by dennisbader** [comment]
@madtoinou thanks for the explanation, and I agree.

@hkogel out of interest what encoding of the time stamps/lags would you have in mind?

**Comment by madtoinou** [comment]
I agree with you that it might not be very intuitive but continuing on your example of encoding the number of years since the beginning of the timeseries. Let's assume that the values are sampled at a monthly frequency, the ts starts in January and the model uses a lag of 2 (we look at sample -1 and -2 to predict timestamp 0). When producing the forecast for January (distant in time), the model will see that the last two samples were in "year X since the beginning of the ts". When predicting February, it will be aware that the transition occurred between sample -2 (year X) and sample -1 (year X+1, January). This "time trend" encoding can be very powerful if it's not aligned with the calendar year and correlated with some kind of external events.

I think that what you're describing with "future_covariates of lag 0" would indeed correspond to what you desire: a covariate at the forecasted timestamp that won't be lagged. If you want to be able to run some sanity check on this covariate, you can generate it outside of the model and then provide it when calling `fit()/predict()`.

**Comment by hkogel** [comment]
Yes, you are right! When changing the frequency of the series the two lags you refer to can be quite helpful (although I would probably think about modelling this using some type of monthly seasonality, along the lines of categorical month feature/month dummies). It is always interesting to think about alternative modelling perspectives on the same situation.

Thank you for the tip on how to run the sanity check. This is helpful!

**Comment by madtoinou** [comment]
Glad to be of help, always nice to explain what is happening under the hood so that users can better leverage the features!

Closing this for now, don't hesitate to open another issue you have any additional questions.
