### ISSUE TITLE
ignoring nan values ​​in dataset

### ISSUE THREAD

**Issue by rumeysskara** [unit8co/darts#1691]
Filling with different methods for the nan values ​​in my dataset negatively affects my estimates. Throwing nan values ​​in my dataset causes some days to be missing. This causes an error for missing days. Is there a method to ignore missing hours?

**Comment by madtoinou** [comment]
Hi,

Darts `TimeSeries` requires regularly spaced values in order to function properly. You could maybe try some of the following to see if it solves your problem:
- if you have few missing hours, you can use `TimeSeries.longest_contiguous_slice()` to train your model on the longest ts without missing values
- if the missing hours are regularly spaced, you could try to use a custom Calendar/freq for your `TimeSeries`, see the code snipped in this [issue](https://github.com/unit8co/darts/issues/1650)
- if you think that shifting the values will not have a detrimental impact on the models, you could replace your TimeIndex with an IntegerIndex (the `time_index` won't contain `pd.Timestamp` but integers.
- try some custom techniques to replace the `NaN` values
