### ISSUE TITLE
Conformal Predictions

### ISSUE THREAD

**Issue by dennisbader** [unit8co/darts#1704]
Conformal predictions could be a valuable addition to darts.
It would require some brain storming/planning of how (or if) we can integrate this into our API / extend the API.  

Some links: 
- https://valeman.medium.com/probabilistic-forecasting-with-conformal-prediction-and-neuralprophet-af9c87901d94
- https://towardsdatascience.com/time-series-forecasting-with-conformal-prediction-intervals-scikit-learn-is-all-you-need-4b68143a027a

**Comment by lsorber** [comment]
For those interested, Conformal Tights is a Python package that adds conformal prediction to Darts: https://github.com/radix-ai/conformal-tights

**Comment by dennisbader** [comment]
Working on it.

**Comment by AugustComte** [comment]
Could you add a facility for weighting within the Naive approach? I find that to be useful.

**Comment by dennisbader** [comment]
Hmm.. For the first version probably not (to keep things simple, it's already getting quite big ;) ). But the goal is to make it easy to define a custom CP model/class with the ability to customize how to calibrate the intervals based on the residuals.

**Comment by AugustComte** [comment]
That makes sense; I also found it was a large amount of work, especially with PyTorch models. But then I was trying to hack PUNCC and MAPIE...  

I'm unsure if this is useful, but I have found this YouTube channel a useful reference: https://github.com/mtorabirad/MLBoost

Anyhow, thank you for the update, Dennis. I'm excited about this. We use darts in production, and your work is greatly appreciated!

**Comment by dennisbader** [comment]
It took a while, but conformal prediction has been added now with #2552 :) 🚀

**Comment by pfwnicks** [comment]
@dennisbader 

> Hmm.. For the first version probably not (to keep things simple for a start, it's already getting quite big ;) ). **But the goal is to make it easy to define a custom CP model/class with the ability to customize how to calibrate the intervals based on the residuals.**
> 
> **After the first version, we're more than happy to further improve / expand on it.**

Any updates on how to perhaps define a custom CP model/class? Otherwise perhaps if anyone is looking to implement some additionally Conformal Models/Frameworks. Specifically perhaps addressing the way in which we are calibrating the conformal models.

Some that would be nice to have would be:

Ensemble Batch Predictive Interval (EnbPI) -[ Xu, C., & Xie, Y. (2021). Conformal prediction interval for dynamic time-series.
In International Conference on Machine Learning (pp. 11559–11569). PMLR.](https://proceedings.mlr.press/v139/xu21h.html)

Sequential Predictive Conformal Inference (SPCI) - [Xu, C., & Xie, Y. (2023). Sequential predictive conformal inference for time
series. In International Conference on Machine Learning (pp. 38707–38727). PMLR.](https://arxiv.org/abs/2212.03463)

Quantile Regression Averaging - [Nowotarski, J., & Weron, R. (2015). Computing electricity spot price prediction
intervals using quantile regression and forecast averaging. Computational Statistics,](https://link.springer.com/content/pdf/10.1007/s00180-014-0523-0.pdf)

QR-CP Ensemble as outlined in section 3.2.6 of  [O'Connor, C., et al. (2025). Conformal Prediction for Electricity Price Forecasting in the Day-Ahead and Real-Time Balancing Market ](https://www.arxiv.org/pdf/2502.04935)

Perhaps O'Connor et al.'s [jupiter notebooks](https://anonymous.4open.science/r/PEPF_Conformal-C0AF/Conformal%20Prediction%20Forecasting%20Library/EnbPI_SPCI_DAM.py) which they have made available through github can be of some assistance as well in this matter?
