### ISSUE TITLE
[BUG] RuntimeError: No precision set

### ISSUE THREAD

**Issue by rishi-a** [unit8co/darts#1718]
**Describe the bug**
Fitting the NBeats model results in ```RuntimeError: No precision set```

**To Reproduce**
1. Follow the official documentation of darts here: [Quickstart Guide](https://unit8co.github.io/darts/quickstart/00-quickstart.html#A-toy-example-with-two-series )
```
from darts.models import NBEATSModel

model = NBEATSModel(input_chunk_length=24, output_chunk_length=12, random_state=42)

model.fit([train_air_scaled, train_milk_scaled], epochs=50, verbose=True);
```
2.  Follow the tutorial as given with the same dataset, i.e. the _AirPassengersDataset, MonthlyMilkDataset_

**Expected behavior**
I expected results as shown in the Quickstart guide. 

**System:**
 - Python version: 3.9.12
 - darts version: 0.24.0

**Comment by rishi-a** [comment]
Resolved it temporarily by upgrading Pytorch Lightning to the latest version. Not sure if that was the actual solution to the problem as well.

**Comment by helenehanyu** [comment]
I ran into the same issue. Updated Pytorch-lightning. However, I can not use optuna with the latest version of PyTorch-lightning.

**Comment by dennisbader** [comment]
Yes, the PyTorch-Lightning (PTL) version was most likely the root cause for this issue. I believe PTL versions shortly before 2.0.0 should work fine as well.

@helenehanyu it should work if you replace Optuna's`PyTorchLightningPruningCallback` with the one proposed in our example description [here](https://unit8co.github.io/darts/userguide/hyperparameter_optimization.html#hyperparameter-optimization-with-optuna) (the link is not formatted well in docs unfortunally, I'll fix that soon. Here is the [link](https://github.com/optuna/optuna-examples/issues/166#issuecomment-1403112861)).

**Comment by helenehanyu** [comment]
Thank you @dennisbader , now it works.
