### ISSUE TITLE
Make setup lighter

### ISSUE THREAD

**Issue by plorenzatto** [unit8co/darts#176]
**Is your feature request related to a current problem? Please describe.**
Currently the default setup of has ~2.4 GB of dependencies. This make it unusable for AWS lambdas or other resource constrained environments.

**Describe proposed solution**
Change the setup so that the heaviest dependencies can be optionally installed:
Eg:
```
pip install u8darts[core] # Bare minimun
pip install u8darts[torch] # ~1.5G (1,4G torch +74M caffe2 + (14+3.4)M tensorboard)
pip install u8darts[fbprophet] # ~500M (31M  fbprophet + 474M pystan)
pip install u8darts[statsmodels] # 42M 
```

**Comment by TheMP** [comment]
Hi @plorenzatto, 

thank you for bringing this up - this is a very good point that's been also in our backlog for a while already.

Is it something you would like to maybe contribute yourself/are you okay with waiting until we deliver this on our side?

**Comment by plorenzatto** [comment]
I'm planning to work on and send a PR when it's ready.

I have some questions about this:
* Which functionalities/modules must absolutely work with the default installation?
* How did you originally thought of solving this issue?

**Comment by plorenzatto** [comment]
@TheMP I'm working on #177 on this. Could you give me some input on the points that I mentioned in the previous message?

**Comment by pennfranc** [comment]
@plorenzatto Thanks a lot for contributing, I think your proposed changes could be very useful! I think making torch and fbprophet optional like you suggested makes sense. But I'm a bit unsure when it comes to statsmodels, since in addition to being used in 3 models, it is also used in some functions from our `statistics` module.

I believe these parts should work without any compromises in the core version:
- `TimeSeries` class
- `backtesting` module (without TorchForecastingModel support)
- at least some models from the `models` module
- `preprocessing` module
- `utils` module (except the torch part)
- `metrics` module

Pretty much everything except some of the more fancy forecasting models for now I believe.

**Comment by plorenzatto** [comment]
I agree with the general idea @pennfranc.

Indeed `statsmodels` is a dependency of `metrics` via `statistics` so better to keep it in the main requirements.

I have some doubts:
* `darts/tests/test_dataset.py` depends on `..models.torch_forecasting_model._TimeSeriesSequentialDataset` not sure if it's meant to be `torch` specific or not.
* `backtesting.explore_models` uses `AutoARIMA` and `Prophet` by default. Can we remove them?

**Comment by pennfranc** [comment]
Good points:
- This is definitely specific to our 'TorchForecastingModel' since it tests a subclass of ours of a `torch` class (`torch.utils.data.Dataset`). The naming of this test case could probably be made to better reflect this fact.
- Yes, I think we can remove them. Although it would be nice to replace `AutoARIMA` with `ARIMA`.

**Comment by dboyleitrs** [comment]
Hi - Just wondering if there is an estimate when this change might be in place. Sorry I'm not helping with the work but would like to use the u8darts library in production but previously mentioned dependencies create too large of a Docker image.

**Comment by hrzn** [comment]
@dboyleitrs We are evaluating our options to solve this issue. Hopefully we should be able to release this within a couple of weeks or so.

**Comment by hrzn** [comment]
This is implemented in develop, and will be part of the next release:
* `pip install u8darts` installs core only
* `pip install u8darts[all]` installs everything
* `pip install u8darts[torch]` installs core + torch models
* `pip install u8darts[fbprophet]` installs core + Prophet
* `pip install u8darts[pmdarima]` installs core + AutoARIMA
