### ISSUE TITLE
[BUG] TopDownReconciliator modifies Top forecasst

### ISSUE THREAD

**Issue by PL-EduardoSanchez** [unit8co/darts#1778]
**Describe the bug**

I'm trying to reconcile some hierarchical forecast with Top-Down approach using `TopDownReconciliator`, but the top time series gets also modified. I'm aware there were similar issues in the past, in which something like this happened depending on the order of the time series in the object with `TimeSeries` (https://github.com/unit8co/darts/issues/1582), but in my case the behaviour is order-independent and I'm not using that version of darts.

**To Reproduce**

Here is the code where I define a `TimeSeries` object with three time series and a simple hierarchy, reconcile the forecast with `TopDownReconciliator` and the top series gets modified:

```python
# imports
import pandas as pd
from darts.dataprocessing.transformers import TopDownReconciliator
from darts.timeseries import TimeSeries

# define time series in a pd.DataFrame
df_ts_raw = pd.DataFrame(data={"date": ["2022-02-28",
                                        "2022-03-31",
                                        "2022-04-30",
                                        "2022-05-31",
                                        "2022-06-30"],
                                "ts_1": [671.450520,
                                        780.584530,
                                        695.618301,
                                        837.410714,
                                        616.029596],
                                "ts_2": [383.85076871,
                                        412.18267353,
                                        401.97344016,
                                        416.19073302,
                                        488.0563728],
                                "ts_top": [1228.1294012,
                                           1100.9604,
                                           1045.31923,
                                           1394.89629,
                                           928.9595]})
# transform date column to datetime
df_ts_raw.date = pd.to_datetime(df_ts_raw.date)

# transform pd.DataFrame to TimeSeries
ts_raw = TimeSeries.from_dataframe(df=df_ts_raw,
                                   time_col="date",
                                   value_cols=["ts_1", "ts_2", "ts_top"])
# apply hierarchy
ts_raw = ts_raw.with_hierarchy(hierarchy={"ts_1": "ts_top",
                                          "ts_2": "ts_top"})

# initialise instance of TopDownReconciliator
reconciliator = TopDownReconciliator()

# fit and transform
reconciliator.fit(series=ts_raw)
ts_reconciled = reconciliator.transform(ts_raw) 

# print differences of "ts_top" between df_ts_raw and the reconciled time series
print(f'{ts_reconciled.pd_dataframe().reset_index()["ts_top"] - df_ts_raw["ts_top"]}')
```

being the output:

> 0    1.095486
1    0.982052
2    0.932420
3    1.244242
4    0.828628
Name: ts_top, dtype: float64

I modified the order of the columns (e.g. introducing `"ts_top"` before `"ts_1"` and `"ts_2"` in the dictionary to define `df_ts_raw` and modifying accordingly `value_cols` in the definition of `ts_raw` just in case), but the result is exactly the same.

**Expected behavior**

If I understood properly the approach, the time series `"ts_top"` shouldn't get modified after the Top-Down reconciliation, so the output of the previous code should be:
> 0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: ts_top, dtype: **float64**

**System:**
 - OS: Windows 10
 - Python version: 3.9.13
 - darts version: 0.24.0
 - pandas version: 1.5.3

**Comment by Loudegaste** [comment]
Hi @PL-EduardoSanchez, thanks for reporting this behavior :) Looking into the code and comparing it with [the text reference ](https://otexts.com/fpp3/reconciliation.html), the origin of the problem seems clear: 
Forecast reconciliation works on the assumption that sum(bottom_series)=top_series, which is not the case in the example you provided. I got `(df_ts_raw.ts_top-(df_ts_raw.ts_1+df_ts_raw.ts_2)).abs().sum() = 633`.

 In the code, the weights are computed like w_i=sum(ts_bottom_i)/sum(ts_top).

I think there are 2 approaches for tackling issues where the sum doesn't match:
* **like it's done in the code:** It is more robust to situation where the equality holds true but with some time shifts, but will be less accurate when the relationship is approximate. I also see edge cases with negative values and null sums.
* **using regular time-series projection:** This is mathematically more rigorous but I think it moves away from the logic of the original concept of TS grouping and is sensitive to small time mismatches.

@dennisbader, @madtoinou, what do you guys think ?

**Comment by PL-EduardoSanchez** [comment]
I see.

My understanding was that you compute the weights as you mention and then apply the weights just to the bottom series. If I understood properly, once you recalculate the bottom series applying these weights, you then recalculate the top series by summing the reconciled bottom series. Is this correct? Thanks!
