### ISSUE TITLE
How to evaluate model with missing values dataset

### ISSUE THREAD

**Issue by mbenami** [unit8co/darts#1847]
Hi Thanks for this great repo 
little bit new to the Time series 
currently working on forecasting and on my dataset I have some missing values 
for now, I fill them with the `fill_missing_values` function
then split to train/test and train `NBEATSModel` model and eval with `mape` and `r2_score`

my question is that in the evaluation of the test dataset, some of the points are not the original and came from the `fill_missing_values` function 
how I can know how good the model was only on the initial points? 
feels to me that evaluating on interpolate point is a little bit of cheating

**Comment by madtoinou** [comment]
Hi @mbenami,

You can split your original `TimeSeries` into several ones (so that there is no missing values within each ts) and then call the metric on the predicted and the split series: darts will take care of aligning the time indexes and will compute the metric only between the values available in both series (thanks to the default value of `intersect=True`). You can tune the way the values are aggregated with the `reduction` and `inter_reduction`).
