### ISSUE TITLE
Question about darts usage

### ISSUE THREAD

**Issue by Jonathan-87** [unit8co/darts#1852]
Hi,

I dont' know if it's better to ask a question here or on the gitter canal. So for now, I have asked the question at both places. Which place is best recommended for this king of questions ?

I have data in pandas dataframe form for different centers that are based in different regions (areas). Each centers have started delivering services at different moments in time. The goal is to do long term forecast of the active number of person receiving services for each centers. Because we know that centers that are in the same regions may shared some similarities, I was thinking about adding the regions as a hierarchy. For this problem, I would like to build a global model.

Here my questions : 

1. I have read the documentation, but I'm not sure that I understand all the differences in darts between a mutiple time series and a multivariate time series. In my case, intuitively my thinking is that because each series starts at different times then I would need to consider them as multiple time series but is it the case ? When I read the documentation the autralian dataset was considered as multivariate time series with the hierarchy so I'm quite confused now.
2. Is there an efficient way to convert pandas dataframe containing multiple time series by centers to accomodate darts format ? Do you have reference or example about this ?
3. Because each centers have started delivering services at different times (ex: center A in 2010, center B in 2015), do I need to add rows for center B because it wasn't in service in 2010 ? If yes, do I need to fill those news rows for center B with zeros because it wasn't in service in 2010 ? I'm able to do this, but was wondering if there is a way to do this efficiently with Darts ?
4. Because we know that centers that are in the same regions may shared some similarities, does a hierarchy of the centers in regions can help ? Is it possible to add hierarchy for multivariate time series and multiple time series ? Do you have an example ? 
5. If I'm creating a global model and for some center we don't have access to a long history so we can't make the output_chunks equal the horizons of forecast need, but for the others we have long history. How can we treat this case in darts ?
6. I understand that darts will not forecast covariates if we add them when forecasting. Darts will produce multiple-step forecast based on what they learned if the forecast horizons is less or equal to output_chunks. In that case, we need to forecast also the covariates if we need to forecast more than the output chunks. The aspect I don't understand is how darts treats the case when we add different features to encode the dynamic of the target time series (ex: lags, rolling/expanding/weight sum of the target). Does darts implement a strategy to update the different features (ex: recursive) because those features will not be available at prediction time ? Do you have reference or example about this ?

Regards,

**Comment by dennisbader** [comment]
Hi @Jonathan-87, and thanks for writing. Both places are fine for this (although gitter might be slightly better).

1. You are correct, it's a **multiple** TimeSeries problem. We describe the difference [in this section](https://unit8co.github.io/darts/userguide/timeseries.html#multivariate-time-series-vs-multiple-time-series) of our guide on TimeSeries (just if you haven't read it). Let me know if it's still unclear.
2. Yes, you can use [TimeSeries.from_group_dataframe()](https://unit8co.github.io/darts/generated_api/darts.timeseries.html#darts.timeseries.TimeSeries.from_group_dataframe). [Here](https://unit8co.github.io/darts/examples/15-static-covariates.html#4.-Extract-a-list-of-time-series-by-groups-from-a-DataFrame-using-from_group_dataframe()) is also an example of how it's used.
3. No, you don't have to do that. With multiple TimeSeries (a list of TimeSeries) the series can have any start/end points (even different frequencies) as long as they fulfill the model time span requirements.
4. Hierarchical reconciliation only works on multivariate problems (and here we chose multiple time series). You can always try out how the multivariate case performs but then you'll have to deal with non-overlapping time index, stacking /concatenation of the series, ... 
However, using `TimeSeries.from_group_dataframe()`, you will have the area encoded as static covariates in your series. `series.static_covariates` ([here](https://unit8co.github.io/darts/examples/15-static-covariates.html) the guide on static covariates). You can use a model that uses this information (all RegressionModels, TFTModel, D/NLinearModel, make sure to convert non-numeric static covariates to numeric, as described in the static covariates guide).
5. I assume the series are too short for training? In that case, you might either decrease the output chunk length, or not use the too-short series for training. At prediction time you can add them back again to the list of `series`.
6. Yes, darts does not forecast covariates. Only the encoders added at model creation with `add_encoders` are dynamically generated by models based on the forecasting horizon `n`. All other user-supplied covariates have to be known in advance (e.g. future covariates, and / or past covariates for larger forecasting horizon `n`  relative to `output_chunk_length`, an example for these requirements can be found [here](https://unit8co.github.io/darts/userguide/covariates.html#covariate-time-span-requirements-for-local-and-global-forecasting-models) for the TorchForecastingModels). For longer forecasting horizons `n > output_chunk_length` the model consumes it's own target predictions in an auto-regressive way to be able to predict all points.

**Comment by Jonathan-87** [comment]
Hi @dennisbader thank you for this clear explanation.

For point 3), when doing a global model I'm not sure to understand how do you treat the fact that the series are not aligned behind the scenes considering that many models don't accept missing values ? 

For point 5), yes some series are shorter (ex: 3 years) and for other they are in service since many years and I need to forecast about 5 years. My thinking was to do a global model and maybe test transfer learning for them.

For point 6), my understanding is with n­ > output_chunk_length then I need to first forecast the regressors as stated in the documentation. ­However, for machine learning models like the RegressionModels class I have come across a discussion on gitter that make me confused, it stated that when using output_chunks_length > 1 and multi_models=False then the model is not going to predict in an auto-regressive way. My question is then how the model predict if output_chunks_length > 1 ? For example, if output_chunks_length = 2 which target will be used to predict y(t+1) and y(t+2) ?

In the future is it planned to add different types of multi-step strategy (ex : DirRec) when forecasting ?

**Comment by dennisbader** [comment]
For point 3) We explain it in [this section](https://unit8co.github.io/darts/examples/01-multi-time-series-and-covariates.html#Training-a-Model-on-Multiple-Time-Series). Let me know if it's unclear.
Yes, missing values should be avoided:
- Missing values/holes at the beginning or end of each series can just be dropped. ([TimeSeries.strip()](https://unit8co.github.io/darts/generated_api/darts.timeseries.html#darts.timeseries.TimeSeries.strip))
- Missing values within the series can either be filled ([MissingValuesFiller](https://unit8co.github.io/darts/generated_api/darts.dataprocessing.transformers.missing_values_filler.html#missing-values-filler)), or you split the time series into parts without gaps (for example when you have large gaps, see [TimeSeries.gaps()](https://unit8co.github.io/darts/generated_api/darts.timeseries.html#darts.timeseries.TimeSeries.gaps), [TimeSeries.longest_contiguous_slice()](https://unit8co.github.io/darts/generated_api/darts.timeseries.html#darts.timeseries.TimeSeries.longest_contiguous_slice))

For point 5) Yes, a global model with meta/transfer learning sounds like a good approach. Also regarding the "series in service since many years" you can also use the approach described above.

For point 6) Yes, if you have to forecast the covariates/regressors, if they are not available at prediction time. 
Regarding the multi_models=False: 
- we discussed the difference between multi_models=False/True in [this issue](https://github.com/unit8co/darts/issues/1646#issuecomment-1477507106). Let me know if it's unclear.
- from the explanation avove, multi_models=False **also predicts auto-regressively if n > output_chunk_length**

So far DirRec has not been in our backlog, but it looks like an interesting approach. We'll need to investigate more but it could be something exclusively for Regression Models. I'll add it to the back-log to keep track of this.

**Comment by Jonathan-87** [comment]
Hi @dennisbader thank you very much for those explanations it's very helpful. It answered all my questions.
