### ISSUE TITLE
Support apache arrow

### ISSUE THREAD

**Issue by heury** [unit8co/darts#1947]
**Is your feature request related to a current problem? Please describe.**
Apache arrow can do zero copy and Pandas and Polars support apache arrow.
So, I think Darts can be very fast and use less memory if it supports apache arrow.

**Describe proposed solution**
Make time series to use apache arrow.

**Describe potential alternatives**
Make dataset to use Pandas and Polars. This is how I am using it now.

**Additional context**

**Comment by heury** [comment]
Yes. Many data analysis tool- pandas, polars, duckdb now support apache arrow. Apache arrow support zero copy. So, it use less memory and exchanging data between them are quite fast. I made my own dataset using polars and duckdb for my project and it works well. So, I think if make timeseries rely on apache arrow instead of xarray, it will improve performance.

**Comment by madtoinou** [comment]
I don't think that PyArrow is a suitable replacement for xarray in the context of darts: the data associated with timeseries forecasting are homogeneous and the benefits of PyArrow seems to be focused on the manipulation of heterogeneous data & memory management.

It could eventually be relevanr to use for the datasets loading but the gain would be very marginal as thse are supposed to be converted to `TimeSeries` in order to leverage any darts features.

WDYT @dennisbader?
