### ISSUE TITLE
[BUG] historical_forecast not possible with AutoARIMA

### ISSUE THREAD

**Issue by leoniewgnr** [unit8co/darts#1963]
**Describe the bug**
In my understanding, it should be possible to predict unseen data with a fitted AutoARIMA model without retraining, but it gives an error. Please correct my understanding if this is not the case.

**To Reproduce**
```
from darts.models import AutoARIMA

model = AutoARIMA()
model.fit(train_series)

# start is at 2pm 10 days later than start of validation set
start = val_series[0].start_time() + pd.Timedelta(days = 10, hours = 14)
yhat = model.historical_forecasts(series = val_series[0], forecast_horizon = 33, start = start, stride = 24, retrain = False)
```
```
ValueError: FutureCovariatesLocalForecastingModel does not support historical forecasting with `retrain` set to `False`. For now, this is only supported with GlobalForecastingModels such as TorchForecastingModels. For more information, read the documentation for `retrain` in `historical_forecasts()`
```

**Expected behavior**
I expect to do forecasts with the fitted model every day at 2pm for next 33 hours

**System (please complete the following information):**
 - Python version: 3.10.10
 - darts version: 0.25.0

**Comment by madtoinou** [comment]
Hi @leoniewgnr,

`AutoARIMA` and `ARIMA` are two different implementations of the same model; `ARIMA` supports `historical_forecasts()` without retraining whereas `AutoARIMA` doesn't. Since darts' `AutoARIMA` is a wrapper around [pdmarima.AutoARIMA](https://alkaline-ml.com/pmdarima/modules/generated/pmdarima.arima.AutoARIMA.html), I don't think that making it support "transferable" historical forecast is a priority.

You could probably use `AutoARIMA` to find the best parameters on the series and use them to train an `ARIMA` model that you would then use to perform historical forecasts.

**Comment by juste97** [comment]
I noticed that the auto statsforecast models include an additional forecast method that would allow for an iterative testing set, which could work well with historical_forecast. 

There is also a forward method intended for completely new series. 

These could be a wonderful addition to historical_forecast 😃

**Comment by madtoinou** [comment]
Thanks @juste97, this is nice to hear!. 

I opened #2281 to keep track of this improvement. Would you have time to implement it?
