### ISSUE TITLE
[BUG] ShapExplainer not working for models fitted with multiple timeseries

### ISSUE THREAD

**Issue by vinicius-alves** [unit8co/darts#1964]
**Describe the bug**
I reproduced the ShapExplainer's example code in https://unit8co.github.io/darts/generated_api/darts.explainability.shap_explainer.html
with a slightly change, using multiple timeseries and the explainer broke.
It gave an error:

> ValueError: `background_series` must be provided `model` was fit on multiple time series.

**To Reproduce**
`from darts.datasets import AirPassengersDataset`
`from darts.explainability.shap_explainer import ShapExplainer`
`from darts.models import LinearRegressionModel`
`series = AirPassengersDataset().load()`
`model = LinearRegressionModel(lags=12)`
`#here the change`
`model.fit([series[:-36], series[:-36]])`
`shap_explain = ShapExplainer(model)`
`results = shap_explain.explain()`
`shap_explain.summary_plot()`
`shap_explain.force_plot_from_ts()`

**Expected behavior**
It should show a plot of shap values

**System**
 - Python 3.11.4
 - darts 0.25.0
 - Windows 10

**Comment by madtoinou** [comment]
Hi @vinicius-alves,

As indicated in the error message, since you train your model with several series, you need to provide a value for the `background_series` argument of the `ShapExplainer` ([doc](https://unit8co.github.io/darts/generated_api/darts.explainability.shap_explainer.html#darts.explainability.shap_explainer.ShapExplainer)).

You could use either the same series as the one used for the model, or just one of them.
