### ISSUE TITLE
Do we need to scale the covariates

### ISSUE THREAD

**Issue by mchirsa5** [unit8co/darts#1978]
Hi folks,

I am very new to the machine learning, and I am trying to forecast the wind power based on different covariates, i.e. wind speed, wind direction, temperature and air pressure.

As far as I'm concerned, the neural network-based models need to scale all the features into to normalise the data so that the training is improved, accurate, and faster. So I need to normalise these data (wind speed, wind direction, temperature and air pressure) into the same scale.

As I understand, in DARTS, these features (measured wind speed, wind direction, temperature and air pressure) can be represented as covariates as they provides an external information to the model. So, I would like to ask if I need to normalise/ scale these covariates as done in the normal neural network-based models?

Thank you for all suggestions.

**Comment by madtoinou** [comment]
Hi @mchirsa5,

Darts' deep learning models generally also process the covariates using neural networks, scaling them prior to training the model is in general a good practice to facilitate the gradient descent but it ultimately depends on the model architecture.

You can find examples in the following notebook: [TCNModel example](https://unit8co.github.io/darts/examples/09-DeepTCN-examples.html#Daily-energy-production).

**Comment by mchirsa5** [comment]
Thank you @madtoinou.

I have checked the notebook that you recommended. As presented in the example, it shows that the past covariates are all scaled over the entire dataset. However, in the ANN-based model, only the training data should be scaled as scaling the entire dataset can lead to the information leakage.

Thus, I would like to ask how should we perform the scaling in DARTS for the future covariates?

Also, as presented in the notebook, we use trained series as input for model.predict(). However, shouldn't we use test series as input for the model.predict()?

Cheers

**Comment by madtoinou** [comment]
For the target series, I agree with you, the Scaler should be fitted only on the training data. A lot of the Darts' example notebooks contain this mistake and we are addressing it. 

For the covariates, it depends on what is contained in your series and which operations you perform afterward:
- for past covariates, if you use `predict()`, then you should already know all the values in advance and there is no information from the future to leak. If you use `historical_forecasts()`, then it can become a problem and some issues were opened to accept data transformers as argument to apply them on the sliding/expanding window.
- for the past covariates, if they contain encoding of some attributes of the time index, there is no information to leak either. If they contain measurments of another phenomenon, then yes, it is a problem and the training/validation split must occur before fitting the data transformer.

The series passed to `predict()` will dictate which timestamps the model will predict, namely the `n` steps after the last entry in the series. In order to obtain forecasts aligned with the test set, you indeed need to pass the training series to this method.

I hope that everything is clear.

**Comment by mchirsa5** [comment]
Hi @madtoinou,

Thank you for a clear explanation. It is very helpful.

However, I have tried  `scaler.inverse_transform()` with my code but there is an error. The code is actually from the tutorial [https://unit8co.github.io/darts/examples/08-DeepAR-examples.html](url) with a few tweaks.

I first scale both the target and covariates. In this case, I used 4 covariates.
`scaler = Scaler()`
`target_train_scaled = scaler.fit_transform([target_train])`
`covariate_scaled = scaler.fit_transform([multivariate_covariate])`

I then trained the model based on these two dataset using the code in the tutorial.
`my_model = RNNModel(`
`    model="LSTM",`
`    hidden_dim=20,`
`    dropout=0,`
`    batch_size=16,`
`    n_epochs=10,`
`    optimizer_kwargs={"lr": 1e-3},`
`    random_state=0,`
`    training_length=50,`
`    input_chunk_length=20,`
`    likelihood=GaussianLikelihood(),`
`)`

`my_model.fit(target_train_scaled, future_covariates = covariate_scaled, verbose=True)`

`pred = my_model.predict(120, future_covariates = covariate_scaled, num_samples=50)`
`pred = scaler.inverse_transform(pred)`

However, the code showed the error that "ValueError: non-broadcastable output operand with shape (8400,1) doesn't match the broadcast shape (8400,4)"

I assumes that this error happens as it cannot identify which Scaler() should be use (from target for covariates). Could you please advise how to identify the correct form of how to use `scaler.inverse_transform()`
