### ISSUE TITLE
[BUG] LightGBM Feature Importance Always 0

### ISSUE THREAD

**Issue by negodfre** [unit8co/darts#2029]
**Describe the bug**
When utilizing a small number of data points (36 in this case), the feature importance of LightGBM features is 0.
I've tried changing various hyper-parameters and limiting the lags / number of features but the issue still remains.
If I increase the time series length (64 instead of 36) the issue does disappear in LightGBM.
However XGBoost implementation didn't seem to have this issue.
Not sure if I am missing something here or a bug.

![xgboost_model_cyclical_pred](https://github.com/unit8co/darts/assets/26559466/867bd6e2-358a-420a-bbf2-691ea833b578)
![lightgbm_model_flat_pred](https://github.com/unit8co/darts/assets/26559466/636518f1-b86b-4c05-96de-2ab597719119)

**To Reproduce**
```import pandas as pd
import numpy as np

import plotly.express as px

from pathlib import Path
from darts import TimeSeries
from darts.models import Prophet, XGBModel, LightGBMModel
import matplotlib.pyplot as plt

def generate_time_series(n_periods, freq='MS', sine_period=12, cosine_period=18, noise_amplitude=0.5):
    """
    Generates a synthetic time series with sine and cosine components and random noise.
    
    Parameters:
        n_periods: Number of periods (months) to generate
        freq: Frequency of time series, default to 'MS' (Month Start)
        sine_period: Period for the sine component, default to 12
        cosine_period: Period for the cosine component, default to 18
        noise_amplitude: Amplitude of random noise, default to 0.5

    Returns:
        A DataFrame with columns 'ds' for datetime and 'y' for values
    """
    time_range = pd.date_range(start='2010-01-01', periods=n_periods, freq=freq)
    sine_wave = np.sin(2 * np.pi * np.arange(n_periods) / sine_period)
    cosine_wave = np.cos(2 * np.pi * np.arange(n_periods) / cosine_period)
    random_noise = noise_amplitude * np.random.normal(size=n_periods)
    
    synthetic_data = 10 + sine_wave + cosine_wave + random_noise
    df = pd.DataFrame({
        'ds': time_range,
        'y': synthetic_data
    })
    
    return df

df = generate_time_series(n_periods=36, sine_period=1, cosine_period=18, noise_amplitude=0.1)

ts = TimeSeries.from_dataframe(df, time_col='ds', value_cols='y', freq='MS')

#model = XGBModel(lags=[-18])
model = LightGBMModel(lags=[-18])

model.fit(ts['y'])

ts.plot()
model.predict(24).plot()

print("Feature Importance: ", model.model.feature_importances_)
print("Feature Names: ", model.lagged_feature_names)
```

**Expected behavior**
Feature importance for prior lags / features are not all 0 with low number of data points.

**System (please complete the following information):**
 - Python version: [3.10.7]
 - darts version [0.24.0]
 - xgboost version [1.7.5]
 - lightgbm version [3.3.5]

**Comment by madtoinou** [comment]
Hi @negodfre,

First of all, both of your models are relying on only one feature: the lag `-18`. I don't know if it's intentional or not but computing the importance of the feature in this context have quite limited interest. You could maybe use a range of lags instead.

In your example, due to their algorithmic differences, `XGBModel` seems capable of capturing some signals in the training set and effectively uses the input signal (feature `y_target_lag_-18`) whereas `LightGBMModel` does not, hence the importance `0` and the constant forecast. By increase the size of the training set, `LightGBM` becomes able to extract some information and effectively uses the input signal.

Hope that it clarifies it, thanks you for sharing the code snippet and the screenshots.

**Comment by dennisbader** [comment]
Hi @negodfre, as @madtoinou pointed out, the issue comes indeed from having a too small training set for the default LightGBM(Regressor) model.

It looks like your length of your input series is roughly 36. With a minimum lag of [-18] you will have a total of roughly 36 - 18 = 18 training examples. By default LightGBM uses a mininum sample size of 20 to perform a split. So you what you end up is a single bucket which predicts the mean of all training example targets.

Either you increase your the size of your dataset or you have to adapt the `LightGBMRegressor` parameters through the `**kwargs` of the Darts `LightGBMModel`.

See the Darts LightGBMModel docs [here](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.lgbm.html#darts.models.forecasting.lgbm.LightGBMModel) and the LightGBMRegressor docs [here](https://lightgbm.readthedocs.io/en/stable/pythonapi/lightgbm.LGBMRegressor.html#lightgbm.LGBMRegressor.__init__)
