### ISSUE TITLE
Is there a way to create a blank TimeSeries object that you can append (concatenate or stack) to similar to list appending?

### ISSUE THREAD

**Issue by gvas7** [unit8co/darts#2032]
I am trying to use Optuna to test different variations of a list of 10 future covariates.  I like to be able to create a list of covariates in each trial on the fly from a master covariate TimeSeries object and then append the ones I want to use to a `future_covariates` TimeSeries object that would get passed to `fit()` or `predict()`.  If I did something similar with a list, I'd create a blank_list and then append the chosen items to the list:
```
my_list = []
for item in list:
   mylist.append(item)
```

I can't do this with a TimeSeries as it has to have some form of an array.  Is the best way to do this to just create a blank TimeSeries with just dates only (is this even possible) or is there a better pattern here I should try?

I've tried something like this, but it doesn't work because of the blank list and says I'm missing the two positional arguments:

```
    selected_covariates = []
    
    for covariate in covariates.columns:
        if trial.suggest_categorical(f'include_{covariates[covariate]}', [True, False]):
            selected_covariates.append(covariate)
    
    print(selected_covariates)
    
    future_covariates = TimeSeries.stack(*selected_covariates)
```
Thanks.

**Comment by madtoinou** [comment]
Hi @gvas7,

I am assuming that the covariates you want to include in your optuna trial are actually columns/components of a single multivariate `TimeSeries` (hence, a unique and shared time index) and not distinct `Timeseries` with different time indexes.

You can simply use the `__getitem__()` operator to extracts the components you want to use for a given trial with:

```python
# ts_covs is the master TimeSeries containing all the covariates, select_covariates is a list of strings
future_covariates = ts_covs[selected_covariates]
```

If the covariates are stored in separate ts with exactly the same time index and you want to use the `stack` method, you can use the snippet below. However, this is approach is not recommended because you will recreate a new `TimeSeries` at each iteration.

```python
trial_ts = None
# select_covariates is a list of univariate TimeSeries where all the TimeSeries have the exact same time index
for cov in selected_covariates:
    if trial_ts is None:
        trial_ts = cov
    else:
        trial_ts = trial_ts.stack(cov)
```

**Comment by gvas7** [comment]
So simple and I overthought it.  Thank you for taking time to explain this and the first example is what I wanted to do and does exactly what I wanted.  As your package gets more popular, more people like me will show up asking questions like this one :(
