### ISSUE TITLE
Usage and definition of static covariates

### ISSUE THREAD

**Issue by ETTAN93** [unit8co/darts#2047]
I am currently trying to incorporate static covariates in my ML model but I am slightly confused as to the correct way to use it. From the definition in the [documentation](https://unit8co.github.io/darts/examples/15-static-covariates.html), it is written that static covariates are characteristics of a time series which do not change over time, e.g. country. Does this mean that if I am working with forecasting the price of goods in 3 different countries, then my target timeseries should contain 3 components and I would then assign the 3 countries as static covariates to those timeseries?

For my particular use case, can **hour of the day** be considered a static covariate? The hour of the day changes over one particular day but stays constant across different days. 

Also, is it a particular design choice in darts that when you lag your past/future covariates, you have to lag all of them with the same lags? Is there an option to, for example, lag past covariate 1 for [-1,-2,-3] and past covariate 2 for [-4,-5,-6]?

**Comment by madtoinou** [comment]
Hi @ETTAN93,

What you described is correct: if you have a multivariate target series with 3 components, each corresponding to a different country, the series should have 3 static covariates, one for each component. It's also possible to have static covariate shared across all components.

If you have a daily frequency in your series, `hour of the day` could eventually be considered as a static covariate if the values were recorded at the same hour for the whole series but I don't think that I would recommend this choice of covariate.

Since release 0.26.0, it's possible to define component specific lags for the target and past/future covariates in `RegressionModel`. This has not been implemented for the deep learning/torch-based models yet but it's on the roadmap.

**Comment by ETTAN93** [comment]
@madtoinou thanks for the clarification. with regards to your last point about being able to define component specific lags, how would that be done? Is it via the key, value pair in a dictionary as stated in the documentation (not sure if the documentation is up to date)
![image](https://github.com/unit8co/darts/assets/59031005/f8fb1871-a943-4040-a5ce-cc88f996716e)

**Comment by madtoinou** [comment]
The documentation is up-to-date, the component-specific lags should be provided using a dictionary.

For example, for a series with 3 components called `["comp0", "comp1", "comp2"]`, you could use the dictionary `{"comp0":[-2,-3], "comp1":4, "comp2": [-1]}`.

**Comment by dennisbader** [comment]
And just as I side note:
If you have multiple products and some are not available in all 3 countries, it might be better to use a univariate (single component/column) `TimeSeries` per product and then add the Product Type or ID (or some other product characteristic) and the country in which it is sold as static covariates.
