### ISSUE TITLE
Interpreting the forecast results when you are predicting the difference in your target.

### ISSUE THREAD

**Issue by ETTAN93** [unit8co/darts#2052]
Assuming I have a dataframe below and I am trying to do a historical forecast using the **actual_target_diff column and feature1_diff column**:
![image](https://github.com/unit8co/darts/assets/59031005/086ed55d-104c-4ec9-9093-d94788545626)
To simplify things, assume:
i. no lags are involved
ii.  forecast horizon = 2
iii. stride = 1 (i.e. every 15 minutes)

Assume we are now at **2019-08-15 23:45**, every 15 minutes, darts will try to predict the next 2 diff, e.g. darts will use 16.199997 (actual_target_diff) and  0.392746 (feature1_diff) to predict the actual target diff of [14.436005 and -3.311996] at 2019-08-16 00:00:00 and 2019-08-16 00:15:00. 

If we assume that darts predict [13.5 and -3.0], how do I recompute the actual target back from these forecasted differences. I'm not sure about which of the 2 methods below is the right way:

i. Are the forecasted difference relative to the previous point in time? This means to recompute the actual_target from the forecasted difference, it will be **206.567993 + 13.5 for 2019-08-16 00:00:00** and **206.567993 + 13.5 - 3.0 for 2019-08-16 00:15:00.**

ii. Are the forecasted difference relative to the actual target of 206.567993? This means to recompute the actual_target from the forecasted difference, it will be **206.567993 + 13.5 for 2019-08-16 00:00:00** and **206.567993 - 3.0 for 2019-08-16 00:15:00**.

**Comment by madtoinou** [comment]
Hi @ETTAN93,

I am not sure to understand what you are doing. Are you forecasting the target column using the `target diff` and `feat1 diff` or the `target diff` using just the `feat1 diff` data? Is your model created with `multi_models=True`?

The model is completely unaware that it's trying to forecast the difference with respect to a past value (it has no access to it?), but by the way you created your `target diff` column, I would say that the forecasted values should correspond to "difference relative to the previous point in time".

However, I would not recommend trying to forecast such at target due to the complexity added to the problem. Is something preventing you from forecasting the target directly?

**Comment by ETTAN93** [comment]
hi @madtoinou, i am forecasting the target_diff using just the feat1_diff data. I am showing the target column just to show how the target diff was computed. And yes, my model was created with multi_models = True.

The point you made about the model being unaware of a past value makes sense because it doesn't have access to it and only has access to the target_diff col and feat1_diff col. In that case, it makes sense that the forecasted value correspond to the difference at each point in time t=0 and t+1.

I am forecasting the difference to make the timeseries stationary.

**Comment by ETTAN93** [comment]
@madtoinou one more question (unrelated one though), is how do I get darts to print out the **progress bar** of the historical forecast? It used to be able to do that when I set verbose=True in historical_forecasts method. 

If I set verbose = True in model initialization, e.g. lr_model = LinearRegressionModel(verbose=1) 
and verbose = True in historical forecasts, i.e. lr_model.historical_forecasts(verbose=True), it only prints out certain output but not the progress bar. 
![image](https://github.com/unit8co/darts/assets/59031005/647535bf-0314-4a32-9bec-a1e2b743da30)

If I set verbose = False in model initialization and verbose = True in historical forecasts, nothing is printed out at all.

**Comment by madtoinou** [comment]
Using the latest version of Darts (0.26.0), you need to set `verbose=False` when calling `fit()` and then, set `verbose=True` when calling `historical_forecasts()`. If you cannot reproduce this behavior or the latest release, please open a separate issue.

Note that the optimized `historical_forecasts()` (when `retrain=False`) won't display the progress bar since loops were removed.
