### ISSUE TITLE
[Question] Regarding static covariates and `from_group_dataframe()`

### ISSUE THREAD

**Issue by cristof-r** [unit8co/darts#2056]
I am using `from_group_dataframe()` to create multiple time series.
This method creates and adds the specified `group_cols` as static covariates.
However, it also removes these values from the time series.
Therefore, when using a forecaster that does not support static covariates, the forecaster will have difficulties differentiating between the time series, as far as I understood.

What is the best way to use `from_group_dataframe()` with forecasters that don't support static covariates?
Or am I misunderstanding something?

**Comment by madtoinou** [comment]
Hi @cristof-r,

If a model does no support static covariates, you should encode them as a future covariate (highly redundant series since the same value will be repeated many times), group the components (or rows) in the target by static covariates and make sure to match them together. In this scenario, you cannot leverage the `from_group_dataframe` and need to extract the static covariates beforehand.

Is something still unclear?

**Comment by cristof-r** [comment]
Thank you very much.
This also means that if future covariates are not supported, I should encode them as past covariates, right?

**Comment by madtoinou** [comment]
Correct.
