### ISSUE TITLE
[Question] Start argument Confusion

### ISSUE THREAD

**Issue by thuyng-ing** [unit8co/darts#2083]
Hi all, thanks for making the library, it's great and very useful. 

I just started my journey with it, so I am a bit confused here on the `start` argument in the `fit ` and `predict` functions.

From what I understand, the `start` argument is the position/portion of the dataset that we want to train/predict on. But what if I want to start predicting at the start of the dataset (I tried 0 but didn't work). It's because in my use case, in real-time, I want to predict if the current point (1 point) is an anomaly or not, and I will feed WINDOW_LENGTH + 1 points to the trained model for it to predict and score for that point. So, what should I set the `start` value to do so?

Thank you in advance and sorry for my naive question and if I misunderstood something.

**Comment by madtoinou** [comment]
Hi @thuyng-ing,

It's usually not possible to start at the first position of the dataset as your model will need some input values in order to generate the forecasts (unless it relies only on future covariates).

In order to achieve what you described, you'll need some additional historical data in order to be able to start the anonaly detection at the first timestep of your current dataset.

You could further reduce the historical data requirements by fitting the forecasting model before calling `predict()` and not retraining it.
