### ISSUE TITLE
Coefficients in a linear regression model

### ISSUE THREAD

**Issue by ETTAN93** [unit8co/darts#2085]
Is there a way to print out the coefficients that a linear regression model uses after the fit method?

For example, in sklearn, you can use model.coef_ and model.intercept_

**Comment by dennisbader** [comment]
Hi @ETTAN93, yes you can access the underlying model with `model.model` and then the attributes `model.model.coef_`, etc.

With `model.lagged_feature_names` you can find a mapping to the features and lags.

**Comment by ETTAN93** [comment]
@dennisbader thanks. Also, can I check with you what is the idea behind having multi_models = True/False? I understand the concept behind how the model is constructed based on the explanation [here](https://github.com/unit8co/darts/issues/1646).

Assume:
`target_lags = [-2,-1],
output_chunk_length = 3`

My target series is:
![image](https://github.com/unit8co/darts/assets/59031005/adf38d76-4693-407c-93d2-929204779c7f)

If i set **multi_models = False**,  the train set should be:
![image](https://github.com/unit8co/darts/assets/59031005/0bf32f92-4134-4564-89b4-1ac4e67e3d92)
Does this mean that when I run `model.predict(n=3)`, to predict the next 3 timesteps, it will use the features below?
timestamp_utc                     X1                X2     
2022-07-02 06:00:00         13.895996  -6.695999
2022-07-02 07:00:00         -6.695999   2.628006
2022-07-02 08:00:00         -2.628006   5.184006

In comparison, when **multi_models = True**, the train set should be:
![image](https://github.com/unit8co/darts/assets/59031005/eb7d1ca5-3a6e-4c06-828a-1fb43fb1d14f)
And to predict the next 3 timesteps, it will be using model 1 to predict t+1, model 2 to predict t+2 and model 3 to predict t+3. What would the features look like when the prediction is carried out in this case?

Under what scenarios would one use multi_models = True vs multi_models = False?

**Comment by dennisbader** [comment]
Hi @ETTAN93, we recently released a notebook on our regression models that describes this in detail.

You can find the section about `multi_models` [here](https://unit8co.github.io/darts/examples/20-RegressionModel-examples.html#Multi-model-forecasting). It also describes how the lagged data is created for both `multi_models=True/False`.

**Comment by ETTAN93** [comment]
thanks. that documentation makes it a lot clearer what's going on under the hood

**Comment by ETTAN93** [comment]
@dennisbader thanks for the link. didn't realise there was a new documentation that was more comprehensive. 

Based on the explanation about multi_models = True/False, am I correct in understanding that when multi_models = True
![image](https://github.com/unit8co/darts/assets/59031005/47f5f4fe-1fc6-41a7-86ba-8e26fbddea4b)
**The relationship between your target variable at different timepoints is not modelled** since each timepoint is modelled with a different model but with the same inputs. For example, sub-model 1 will only learn about the relationship between:
i. features t-4 to t-1 and the target t0 
ii. features t-2 to t+2 and the target t+2

Compared to when multi_models = False, 
![image](https://github.com/unit8co/darts/assets/59031005/0b5d9e88-71da-4b25-94bb-6b8cfe2ca541)
The 1 model built will learn about the relationship between how the target changes (from forecast 1 to forecast 2) and how the features change (from t-5: t-2 to t-4: t-1)

In the documentation it is stated that multi_models = True tends to yield better results. Why is that the case? If your target has a strong autocorrelation, then using multimodels = False would be a better approach?

**Comment by dennisbader** [comment]
1. The graphs show the prediction process. For training, sub-model 1 and 2 will learn from each possible target time step (e.g. it doesn't move output chunk length points ahead but just 1). Let's assume the input series here was actually your training series, then sub-model 1 would train on target time steps t-2 until t+2. Sub-model 2 will train on steps t-1 until t+3.

2. With multi_models=False, the model will train on target time steps t-1 until t+3

When multi_models=False and output_chunk_length>1, then the model will not use the most recent observed target time step for any horizon < output_chunk_length. Only for the last predicted point, it will use the most recent observed target values.

multi_models=True tends to yield better results, because it contains the multi_models=False (the `output_chunk_length`th sub model) and other dedicated sub models models for all other horizons smaller than `output_chunk_length`.

**Comment by ETTAN93** [comment]
@dennisbader, so based on what we discussed, it should be as below:
![image](https://github.com/unit8co/darts/assets/59031005/88e0a692-96ac-4728-a2e2-f06942ab3935)
Is the representation correct?

So to translate what you said into this diagram, 
i. sub_model 1 will train on t0 to t+3 to predict t+4, then t+1 to t+4 to predict t+5.... 
ii. sub_model 2 will train on t0 to t+3 to predict t+5 then t+1 to t+4 to predict t+6

After the sub_models are trained, when we do the actual prediction, sub_model 1 will use t+5 to t+8 to predict t+9 and sub_model 2 will use t+5 to t+8 to predict t+10.

**Comment by madtoinou** [comment]
The representation is correct.

We usually refer to first predicted time step as t0 (ie, the first value in the chunk of length `output_chunk_length`).

For `multi_models=True`, we obtain:
- sub_model 1 uses t-4, t-3, t-2, t-1 to predict t0
- sub_model 2 uses t-4, t-3, t-2, t-1 to predict t1

Then if `n > output_chunk_length`, model rely on auto-regression:
- sub_model 1 uses t-2, t-1, t0, t1 to predict t2
- sub_model 2 uses t-2, t-1, t0, t1 to predict t3

To forecast what comes after your example series, your description is correct (using your notation).

Observation between `multi_models = True/False`:
i. This is correct, the last value of the first forecasted chunk will be identical.
ii. Correct as well.

Yes, this statement is correct. And in general, `output_chunk_length` should be smaller or equal to `n` in order to maximize performance (there is no reason to have a larger `output_chunk_length`).

**Comment by brianreinke95** [comment]
Hi. I was having another question regarding this subject. I have 12 points to predict, output_chunk_lenght = 1 and multi_model = False. For each point greater than t0 the model will use the forecasted values? t1 will use the forecasted value for t0?

![forecasting](https://github.com/unit8co/darts/assets/28718644/fc31116d-476f-45ae-85bb-fe1597349f39)


Thanks!
