### ISSUE TITLE
Relationship between retrain, stride and train_length in historical forecast method

### ISSUE THREAD

**Issue by ETTAN93** [unit8co/darts#2090]
Hi,

What is the relationship between retrain, stride and train_length in the historical forecast method and how do they interact with one another? Based on the [documentation](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.linear_regression_model.html#darts.models.forecasting.linear_regression_model.LinearRegressionModel.historical_forecasts), it says that when retrain is an int, the model is retrained every retrain iterations. Does stride affect when the retrain happens in any way? Or is it only affecting the number of time steps between the predictions?

Is my understanding correct for the different scenarios below:
Assume my data is in **1 hour** granularity:
i. Retrain = 90, train_length = None, Stride = 24: The model is **retrained every 90 hours with an expanding window** of the historical data? Or is it every 90 days since the stride is 24?
ii. Retrain = True, train_length = 90, Stride = 24: The model is **retrained with a moving window of 90 hours**** of data?

**Comment by madtoinou** [comment]
Hi @ETTAN93,

`stride` is applied to the forecasted `series` before the inner loop of retrain/forecasts, `retrain` takes into account the number of forecasted horizons (in the inner loop).

i. The model will predict `forecast_horizon` every 24 hours. Every 90 predicted `forecast_horizon`, the model is retrained using an expanding window.
ii. The model is retrained before each `forecast_horizon` (spaced by 24 hours), using the last 90 time steps

**Comment by ETTAN93** [comment]
@madtoinou. thanks for the explanation. Just to make sure I got it correct, based on your explanation, if my **forecast horizon = 24, stride = 24**, it means that
i. Retrain = 90, train_length = None: Model will predict 24 timesteps (i.e. 24 hours) every 24 hours (due to stride). Every 90 days (since retrain is 90 and forecast horizon is 24 hours), the model is retrained using an expanding window (since train length is None).
ii. Retrain = True, train_length = 90: Model is retrained every day (since retrain is True and stride is 24) before each 24 hours prediction (since forecast_horizon is 24) using the last 90 time steps (since train_length is 90).

**Comment by madtoinou** [comment]
i. That's correct, retraining will be triggered every 90*12 hours = 1080 hours = 45 days. 
ii. Correct as well.

It feels a bit weird to describe this as a frequency, in particular, I don't see why you would divide by the `forecast_horizon`?

The progress bar (when using `historical_forecasts()` on a single `series`) correspond to the number of `forecast_horizon` that will be predicted and is completely independent from the value of the `multi_models` parameter of the model.

So for a series of length 10, a pre-trained model (lags=3) and forecast_horizon=2, there are only 6 "forecastable" horizons since the first 3 values needs to be used as input and the last one is incomplete (`overlap_end=False` by default). If you use a stride of 2, the bar denominator will be 3.

For your example, impossible to tell without knowing the `lags/input_chunk_length` of the model but it'll probably be less since you did not account for the fact that the first values cannot be forecasted since there is no input for them.

**Comment by ETTAN93** [comment]
i just meant the frequency as how often retraining happens. I see what you mean by there is no need to divide by the forecast_horizon. so if my setup is as below:
i. Data granularity = 15 minutes
ii. Forecast horizon = 3
iii. Stride = 1
iv Train length = None

If I want to retrain every month with an expanding window, I should be setting retrain to 2880 which would give 

retrain * stride =  2880 * 1 = 2880 * 15 minutes (since 1 stride is 15 minutes) = 43200 minutes = 30 days.

Is that correct?

**Comment by madtoinou** [comment]
This is correct.
