### ISSUE TITLE
[QUESTION] How a past_covariates work under the hood?

### ISSUE THREAD

**Issue by guilhermeparreira** [unit8co/darts#2126]
**My General Understanding**
When we use `future_covariates`, they are aligned with the predictions.

For example, for a [RegressionModel](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.regression_model.html#darts.models.forecasting.regression_model.RegressionModel) the tabularization of the target `Y_{t-2}, Y_{t-1}, Y_{t0}` for a future covariate considering lag 0 is `X_{t-2}, X_{t-1}, X_{t0}`. Considering I want to predict two steps, I will also provide `X_{t+1}, X_{t+2}` for predictions `Y_{t+1}, Y_{t+2}`.

However, if I use a `past_covariate`, I have only `W_{t-2}, W_{t-1}, W_{t0}`. 

**Question(s)**
So, how will it predict `Y_{t+1}` and `Y_{t+2}` without having `W_{t+1}` and `W_{t+2}`?
So, how does the tabularization work? 
Can I debug it with a function? 
Does it use `W_{t+0}` to predict `Y_{t+1}` and `W_{t-1}` to predict `Y{t+2}`?

**Additional context**
I am aware that the documentation says that [`models don't use the future values of past_covariates when making forecasts`](https://unit8co.github.io/darts/userguide/covariates.html

**Comment by madtoinou** [comment]
Hi @guilhermeparreira,

You can find an example of how the target series is tabularized in the [regression model notebook](https://unit8co.github.io/darts/examples/20-RegressionModel-examples.html#Lagged-data-extraction). The process is similar for both `past_covariates`/`future covariates`. The extracted values are simply concatenated to the target values, as extra features.

When `output_chunk_length >= 1`, the complexity increase slightly and the underlying process depends on the `multi_models` parameter. You can see the difference in this [notebook's section](https://unit8co.github.io/darts/examples/20-RegressionModel-examples.html#Visualization). For the sake of simplicity, assuming `multi_models=True` in my explanations as it's the default behavior.

Now, a short example with covariates. Let's assume a regression model was created with `lags=[-2,-1], lags_past_covariates=[-3,-2,-1], lags_future_covariates=[0,1], multi_models=True, output_chunk_length=2` and the past/future covariates are called $pc$ and $fc$ respectively.

- By definition, `past_covariates` can only have negative lags. Hence, to forecast $Y_{t+1}$, $Y_{t+2}$ the model will need $pc_{t-2}$, $pc_{t-1}$ and $pc_{t}$ (the last 3 values of the series used to train the model). If `output_chunk_length` was equal to 1, `predict()` called with `n=2`, the model will use auto-regression and expected to be able to access $pc_{t+1}$ (a future value of the past covariates) in order to forecast $Y_{t+2}$.
- `future_covariates` accepts both negative and positive lags, as the information is supposed to be known in advance, including during the forecasted period. Hence, to forecast $Y_{t+1}$, $Y_{t+2}$, the model will access $fc_{t+1}$ and $fc_{t+2}$. Again, if `output_chunk_length=1` and `predict()` is called with `n=2`, the model will use auto-regression and expected to be able to access $fc_{t+3}$ in order to forecast $Y_{t+2}$.
- As for the target values, the model will access $Y_{t-1}$ and $Y_{t}$ to forecast $Y_{t+1}$, $Y_{t+2}$ if `output_chunk_length=2` and `multi_models=True`. $Y_{t-1}$, $Y_{t}$ and $\hat{Y}_{t+1}$ (first predicted value, used during auto-regression to forecast the second value) if `output_chunk_length=1` and `multi_models=True`.

For deep learning model, there is less flexibility on the lags and the model takes `input_chunk_length` values from the `past_covariates` (as if `lags_past_covariates=input_chunk_length`) before the forecasted period and `output_chunk_length` values from the `future_covariates` (as if `lags_future_covariates=output_chunk_length`), aligned with the forecasted period for the target.

Altogether, if you don't have access to future values of the past covariates, you should set `output_chunk_length >= n` so that the model never tries to use auto-regression when `predict()` is called.

**Comment by guilhermeparreira** [comment]
Thank you so much for the detailed answer! 
The point that I was missing was that for using `n>output_chunk_length`, I would need to have future values of past_covariates.

To take advantage of this topic:

Why does `t-1` is not used for the 1st chunk in the first line of the second figure from [this link](https://unit8co.github.io/darts/examples/20-RegressionModel-examples.html#Visualization): 

Is it because `t-1` is the `lag 0`?

**Comment by madtoinou** [comment]
Glad it answers your question.

In the second figure, the model was created with `output_chunk_length > 1` and `multi_models=False` i.e. one model is used to forecast all the positions in `output_chunk_length`.

Since regression models are deterministic ; the same weights applied to the same features (lags) will generate the same output, it's necessary to shift the inputs so that the forecasts are different for each position. Hence, each "lags window" is shifted by `output_chunk_length - 1 - idx_forecast` in order for the model to predict the `idx_forecast` position inside one `output_chunk_length` (0-indexing).

Still in this figure, if `output_chunk_length = 3` and `predict()` was called with `n=3`, the first forecast would use `t-6` to `t-3`, second `t-5` to `t-2` and the third (not visible in the figure) `t-4` to `t-1` i.e. the lags effectively passed at the model creation.

`multi_models=False` was implemented for lightweight models with faster training (since only one set of coefficient needs to be fitted) when `output_chunk_length > 1` but it's recommended to use `multi_models=True`, which generally yields better performance (and considerably simplify the logic between inputs and outputs).

**Comment by guilhermeparreira** [comment]
Thank you for your support!

But what remains unclear for me is that:
with `lags=[-4,-3,-2,-1]`, I expected that they would use `t-4`, `t-3`, `t-2` and `t-1` to forecast t0. However they use t-5 up to t-2, instead. I just pasted here what is not clear for me from Figure 2:
![image](https://github.com/unit8co/darts/assets/13880005/704a0995-cf4f-44b4-a8b8-aa5b2fd3337a)

**Comment by madtoinou** [comment]
I understand that this is counter-intuitive but it's the approach Darts uses to be able to use a single model to forecast several position in one go when `output_chunk_length>1`. This is not the default behavior, it happens only when `multi_models=False`.

**Comment by sanjibeng2** [comment]
For models that support only past covariates, is it so that future value of the covariate is at first predicted and then those are provided to the model to predict the target?

**Comment by guilhermeparreira** [comment]
> I understand that this is counter-intuitive but it's the approach Darts uses to be able to use a single model to forecast several position in one go when `output_chunk_length>1`. This is not the default behavior, it happens only when `multi_models=False`.

I see. Is there any reference to it? Or a documentation that explains why? I would like to know more about it.

**Comment by madtoinou** [comment]
@sanjibeng2 : models never forecast any of the covariates; if `n > output_chunk_length` (hence require auto-regression), the model will expect "future" values of the past covariates and raise an error if it does not extend far enough. The same applies for future covariates as well.

@guilhermeparreira : yes, you can find some illustration of this mechanism in the [regression model notebook](https://unit8co.github.io/darts/examples/20-RegressionModel-examples.html).

**Comment by Gulser** [comment]
Hello,
When n > output_chunk_length and therefore future values for past_covariates have to be included, these values are predictions?

In other words, I understand that when n > output_chunk_length, the difference between past_covariates and future_covariates is that the future_covariates are all known values, while the future values of past_covariates are predictions. Otherwise it would be the same to use one or the other when n > output_chunk_length right?

Thanks.

**Comment by madtoinou** [comment]
Hi @Gulser,

You can find an illustration of the difference between the two [here](https://unit8co.github.io/darts/quickstart/00-quickstart.html#Covariates:-using-external-data).

The future values of `past_covariates` are not necessarily predictions, for example if you start forecasting in the past, some of the historical data you have access to will go beyond the beginning of the forecast horizon and hence be available if `n > output_chunk_length`. On a side note, `future_covariates` can be forecasts provided by other models/sources.

Ultimately, the difference is that `future_covariates` allows "positive lags" (lags into the future) whereas `past_covariates` contains only "negative lags" i.e. in the past with respect to the forecasted period. And when `n > output_chunk_length`, the model will perform auto-regression and the `past covariates` will have to extend enough into the future (ie potentially beyond the first step of the forecast horizon) to extract the lags.

I hope that it clarifies things

**Comment by Gulser** [comment]
Thanks for your answer @madtoinou. 

Regarding Deep Learning models where model takes `input_chunk_length` values from the `past_covariates` before the forecasted period and `output_chunk_length` values from the `future_covariates`, I don't quite understand what would be the purpose of `past_covariates` in this situation. How can the model benefit from these `past_covariates` to predict future values? 

If we were to forecast the future values of these `past_covariates`, and use them as `future_covariates`, I could understand how the model could take advantage of it. But Darts is not doing these forecasts of past covariates. It is an intermediate step that each user should do.

For example, imagine we want to forecast electricity demand (typical example) and we use electricity price as a covariate, but we don't have future prices. How could the model benefit from these past values without previously making a forecast on future prices?

Thanks in advance.

**Comment by madtoinou** [comment]
Similarly to how the model can benefits from patterns in the past values of the target series, it can also leverage the past values of the covariates. In your example, you could think of this as if the model is implicitly/internally modeling the electricity price before forecasting the demand.

If your interested in the future values of the covariates, or would like to explicitly assess if its past values are enough, then yes, training a model to forecast this covariates before feeding it to a second model is the way to go (but increase the complexity of the system).
