### ISSUE TITLE
[INFO] How to pass a dataframe to fit time series in multivariate time series scenario?

### ISSUE THREAD

**Issue by guilhermeparreira** [unit8co/darts#2141]
Hi there!

I have the following dataframe:

![image](https://github.com/unit8co/darts/assets/13880005/0c86f13e-878f-41fd-b894-4589cfffc515)

`h1, h4, h11, h3, h8` are my target
`ipca` is a common `past_covariate` for all targets
`dolar` is a common `future_covariate` for all targets
`h1_volume_estoque` and `h1_val_liq` are specific covariates for `h1` target.

I also want to say that `h1` and `h11` are correlated using `static covariates`.

**Question**
Can I pass all targets at once? (Is there any notebook for it?).

**Additional context**
I found this option:
![image](https://github.com/unit8co/darts/assets/13880005/f57ad4aa-4dff-4d08-be53-5c8f7cbb53f3)
But it provides series by series. However, I have 15 different targets in my real scenario, and I want to simplify my code. 
I am sure that I saw it somewhere, but I could not find it right now.

I also saw it:
![image](https://github.com/unit8co/darts/assets/13880005/8536fca1-91a1-4b8d-afd7-fe6a07607aa5)

However, it is not clear where the target value is supplied, and what `var1` represents.

**Comment by dennisbader** [comment]
Hi @guilhermeparreira.

You can either perform multivariate forecasting (fit/predict all variables jointly at once with a single target series) or multiple series forecasting (fit a single global model on all variables/target series independently and use it to predict all series independently).

- the multivariate case: your target `series` must have all target columns (h1, h4, ...). Use a single past and future covariates series as you described. You can find an example [here](https://unit8co.github.io/darts/examples/01-multi-time-series-and-covariates.html#Training-and-Forecasting-Multivariate-TimeSeries)
- the multiple series case: define 4 `series`, each having only a single target column h1 or h4 or ... Pass them as a list to fit/predict. For each `series` in the list, you must also give corresponding past and future covariates series. So if you want to use these covariates, you have to pass a list of 4 past and future covariates series (in your case it will be the same past/future covariates repeated 4 times)
- static covariates only make sense when using **multiple series**. You could for example have a binary static covariate with `1` for `h1` and `h11` that are correlated, and `0` for the others.
- `var1` is just an example for an imaginary numeric static covariate that is the same (static) per series (`series1` and `series2`).

Multivariate and multiple series forecasting are very different from each other. So I'd suggest to go for the better performing approach, rather than code simplicity.

**Comment by guilhermeparreira** [comment]
Hi @dennisbader,
Thank you so much for the clarification.

I did not realize that there was a difference between the **multiple series** and **multivariate forecasting** in **Darts**.

I just implemented the multivariate case:

**Input:**
![image](https://github.com/unit8co/darts/assets/13880005/ab4fbffe-f38d-4391-9b6c-c019d9c6b611)

**Model (I tested all of them 'by hand'**
![image](https://github.com/unit8co/darts/assets/13880005/3a0216e2-42a3-414f-b20f-94ae6043d51e)

**Auxiliar Function**:
![image](https://github.com/unit8co/darts/assets/13880005/e37c576c-61d4-473e-8c46-6d3a8c695f8e)
![image](https://github.com/unit8co/darts/assets/13880005/c885d89d-184e-4d17-9c9e-1741672060e3)
![image](https://github.com/unit8co/darts/assets/13880005/bb71409f-54bd-495d-9dad-01435ffeccf9)

I got the following results:

![image](https://github.com/unit8co/darts/assets/13880005/9dd6c577-6381-4301-974f-ec2133840201)

which are way worse than my current implementation (I did a `for()`, i.e., passing one variable at a time.), except for **h1** (it was curious for me):
![image](https://github.com/unit8co/darts/assets/13880005/f8e3ed36-6b8a-4996-ae04-733127d47d28)

**Question**
+ Is there something I may be missing for the multivariate scenario?

+ I noticed that whether I remove or include a hierarchy the final result (rRMSE) does not change at all (not even in the last decimal place). Is it because my models don't take into account the possible correlation between the hierarchies?

**Context:
On the docs, I read:
> "These components usually present the same nature (measurement of the same metric) but this is not necessarily the case."
which concerned me a little bit, because my targets don't have the same nature. Even though I scale them.

+ In my current implementation I also look for an exhaustive hyperparameter, lag, and model grid. However, I don't think that the downgrade in performance is lonely due to it.
