### ISSUE TITLE
[BUG] Timeseries-converted Dataframe contains NaN while the original one does not

### ISSUE THREAD

**Issue by lo3me** [unit8co/darts#2149]
**Describe the bug**
After making Timeseries from the dataframe it seems the converted series has NaN values, leading to sckit-learn `ValueError: Input X contains NaN.`

**To Reproduce**
```py
ds = TimeSeries.from_dataframe(df, "open_time", "close", fill_missing_dates=True)
dart_df = ds.pd_dataframe()

print(df.isna().sum())
print("---")
print(dart_df.isna().sum())
```
```
open_time    0
open         0
high         0
low          0
close        0
volume       0
dtype: int64
---
component
close    24
dtype: int64
```
Also If I don't use `fill_missin_dates` I get:
```
The time index of the provided DataArray is missing the freq attribute, and the frequency could not be directly inferred. This probably comes from inconsistent date frequencies with missing dates. If you know the actual frequency, try setting `fill_missing_dates=True, freq=actual_frequency`. If not, try setting `fill_missing_dates=True, freq=None` to see if a frequency can be inferred
```

**System (please complete the following information):**
 - Python version: 3.10.12
 - darts version: 0.27.1

**Additional context**
```py
dm = models.LinearRegressionModel(lags=10, output_chunk_length=1)
dm.fit(train)
preds = dm.predict(len(val))

ds.plot(label="ds")
preds.plot(label="prediction")
val.plot(label="validaiton")
```
```
ValueError: Input X contains NaN.
LinearRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values
```

**Comment by madtoinou** [comment]
Hi @lo3me,

NaNs can be introduced when you convert data from a `pd.DataFrame` into a `TimeSeries` if some dates are missing and the freq argument is incorrectly set as Darts will add the missing time steps.

**Comment by lo3me** [comment]
Hi,
But even if I set the `freq=4H` which is the interval, it adds the missing ones. 
Isn't it better to not automatically change the data when a user does not set any specific argument to fill the missing timestamps?
I think It would be good to have an option for the user to do so maybe using something like [scikit-learn imputers](https://scikit-learn.org/stable/modules/impute.html#imputation-of-missing-values) instead of setting to `NaN`.

**Comment by madtoinou** [comment]
`TimeSeries` class guarantees that:
-  Have a monotonically increasing time index, without holes (without missing dates)
-  Have a well defined frequency ([date offset aliases](https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#offset-aliases) for DateTimeIndex, or step size for RangeIndex)
- [...]

The point of the `fill_missing_dates` argument is precisely to explicitly fail and indicate to the user that some points are missing. If `NaN` are introduced in your dataset when `fill_missing_dates=True` or `freq="4H"`, it means that the time index does not have an entry every 4 hours despite it being the expected frequency of the dataset.

In order to get ride of the `NaN`, you can use the `MissingValuesFiller` ([doc](https://unit8co.github.io/darts/generated_api/darts.dataprocessing.transformers.missing_values_filler.html?highlight=missing)).
