### ISSUE TITLE
How to use darts with bentoml ?

### ISSUE THREAD

**Issue by AyushBhardwaj321** [unit8co/darts#2181]
Hello everyone,
I am trying to use BentoML for model versioning , continuous training and deployment  but there is no documentation available.

Any lead / support is helpful.
Thank You

**Comment by madtoinou** [comment]
Hi @AyushBhardwaj321,

Since Deep learning models of Darts are based on Pytorch Lightning, this section of BentoML documentation should be relevant : https://docs.bentoml.com/en/latest/frameworks/pytorch_lightning.html. You might need to access the "underlying" model stored in the `.model` attribute for Darts forecasting model.
For other models, BentoML seems to provide examples for a variety of frameworks that are also present in Darts here: https://docs.bentoml.com/en/latest/frameworks/index.html (scikit-learn, catboost, lightgbm, gxboost, ...)
