### ISSUE TITLE
[FEATURE] Isolated version of models

### ISSUE THREAD

**Issue by marcelo-bn** [unit8co/darts#2211]
It is essential to have isolated versions for each model.

For example, I only need TFTModel in my project but I have to install ALL the models (>3GB!!).

This is horrible. I have to interrupt my entire workflow to adapt a project with just the parts I want.

**Comment by madtoinou** [comment]
Hi @marcelo-bn,

If you want to use a Darts is a lightweight environment, you can use the onnx format (check the code snippet at the end of issue #553). However, you will be responsible for reshaping/preparing the samples for inference and won't have access to the `TimeSeries` data-structure anymore.

Maintaining a separated version of the library for each model would actually not solve the problem since a lot of dependencies would remain (and it would be not realistically maintainable).

Feel free to fork Darts and remove all the features/models you don't need, hopefully this will reduce the requirements enough so that you can use our TFT implementation with your current constraints.
