### ISSUE TITLE
Hyperparameter Optimization for Lightgbm

### ISSUE THREAD

**Issue by brianreinke95** [unit8co/darts#2212]
Hi. This is the only site I found when searching for hyperparameter optimization: https://unit8co.github.io/darts/userguide/hyperparameter_optimization.html#hyperparameter-optimization-with-optuna 
Those are for NN models. 
About gridsearch:
Each forecasting models in Darts provides a gridsearch() method for basic hyperparameter search. This method is limited to very simple cases, with very few hyperparameters, and working with a single time series only.
I'm looking for a way to tune my multi-series lightgbm model. 
Is there a way? 
Thanks, 
Brian.

**Comment by madtoinou** [comment]
Hi @brianreinke95,

In the documentation, we recommend using other libraries such as `Optuna` or `Ray-tune` to optimize hyper-parameters instead of `gridsearch()`.

The tutorial you linked also applies to regression models such as `LightGBMModel`, you just need to adapt the `objective(trial)` function to train and evaluate the model. Aside from the callback/checkpointing, there is nothing specific to NN.
