### ISSUE TITLE
Purpose of passing target time series to model predict method

### ISSUE THREAD

**Issue by ETTAN93** [unit8co/darts#2214]
Hi,

If my model does not have any target lags, i.e. `target_lags = None`, does it mean that passing the series to the predict method is purely to tell the model where to start the forecast from? If I do not pass series to it, then the model will be forecasting from the end of the training series rather from where I want it to

![image](https://github.com/unit8co/darts/assets/59031005/407f47df-0360-48f9-aadd-7265908982da)

**Comment by madtoinou** [comment]
Hi @ETTAN93,

This is correct, even if the model does not rely on target lags, it'll just use its time index to generate the time index of the forecasts.

So yes, you can still pass a series if you want to shift the first predicted steps (note that here, auto-regression should not affect the quality of the forecasts since the model won't consume its own predictions so the dummy target series might not even be necessary).
