### ISSUE TITLE
Getting ValueError index 0 isn't sufficiently long when using .predict() related to past_covariates

### ISSUE THREAD

**Issue by Allena101** [unit8co/darts#2223]
Hello again! Thanks to your help i am making alot of progress on learning this library

Trying to put alot of the features together i run into a new problem that i cant figure out.

Here is the full error messge:
ValueError: The corresponding past_covariate of the series at index 0 isn't sufficiently long. Given horizon `n=7`, `min(lags_past_covariates)=-1344`, `max(lags_past_covariates)=-4` and `output_chunk_length=3`, the past_covariate has to range from 2023-12-29 12:15:00 until 2024-01-12 12:15:00 (inclusive), but it ranges only from 2020-06-18 08:00:00 until 2024-01-12 12:00:00.

I have no idea why i am getting this error. The past_covariates and target series are made from the same dataFrame (so they have the exact same time index). 

I will post the part of the code that i think is relevant and also list some things i have tried to fix this.

last value has the same dateTime:

train_scaled[-1]:
datetime64[ns]
2024-01-12T12:00:00

covariates_scaled[-1]:
datetime64[ns]
2024-01-12T12:00:00

```py
LGBM_Model = LightGBMModel(
    lags=5,
    lags_past_covariates= { 
                           "el": list((range(-672, -2007, -672))), 
                           "Ksd_temp": list((range(-4, -97, -4))), 
                           "Ksd_precip": list((range(-4, -97, -4))), 
                           "open": list((range(-96, -673, -96))),
                           "close": list((range(-96, -673, -96))),
                           },
    lags_future_covariates = [-2,-1, 7, 14, 21],
    output_chunk_length=3,
    verbose=-1,
    metric="rmse",
)

LGBM_Model.fit(train_scaled,
               past_covariates=covariates_scaled,
               future_covariates=ts_time_and_holiday_future_covariate
               )

# tried both with and without using the past_covariate argument
preds =  LGBM_Model.predict( 7 )

preds =  LGBM_Model.predict( 7,
                            #past_covariates=covariates_scaled,
                            #future_covariates=ts_time_and_holiday_future_covariate
                            )
```

Things i have tried:
1) splicing off a big part of the target feature series so that there would be more past covariates than target feature
2) removing future_covariates (error only occurs with past covariates)
3) reducing the lag features of the past_covariates (still get the same error)

What i have noticed why troubleshooting this issue is that if i increase output_chunk_length to the same value as N in predict then it works. The issue with this is that in this case, i really dont want to train with that big of an output_chunk_length. I also think its not necessary since i found in your DeepTCN tutorial that you have both past_covaraites and your predict value is larger than your output_chunk_length.

This leads me to believe that the issue is caused by something else entirely and I have no idea what it could be.

**Comment by Allena101** [comment]
the key part of the error, as far as i can understand it, is the:
until 2024-01-12 12:15:00 is off by one timeStep (t15). But i have no idea what to do with that info. Also the lags for the the future_covaraites dont raise the same error which i find odd.

**Comment by madtoinou** [comment]
Hi @Allena101,

Since `output_chunk_length < n`, where `n` is the number of values you're trying to forecast, the model is using auto-regression and hence access "future values of the past covariates" (ie. values that comes after the last time step in the target series, see docstring of the `output_chunk_length` parameter).

Since the `past_covariates` series ends at the same time step as the target series, the model cannot get the values corresponding to the `lags_past_covariates` (during the last auto-regression step, to predict the 7th position of the forecasted horizon since the greatest past covariates lags is -4).

The solution is to either increase `output_chunk_length` or change the lags so that the covariates extend far enough.

**Comment by Allena101** [comment]
> Hi @Allena101,
> 
> Since `output_chunk_length < n`, where `n` is the number of values you're trying to forecast, the model is using auto-regression and hence access "future values of the past covariates" (ie. values that comes after the last time step in the target series, see docstring of the `output_chunk_length` parameter).
> 
> Since the `past_covariates` series ends at the same time step as the target series, the model cannot get the values corresponding to the `lags_past_covariates` (during the last auto-regression step, to predict the 7th position of the forecasted horizon since the greatest past covariates lags is -4).
> 
> The solution is to either increase `output_chunk_length` or change the lags so that the covariates extend far enough.

thanks for the quick and pedagogical reply!

What i dont understand about this is why then reducing the target feature does not resolve this issue.

```py
train_cut = train_scaled.drop_before(0.3)

LGBM_Model.fit(train_cut,
               past_covariates=covariates_scaled,
               future_covariates=ts_time_and_holiday_future_covariate
               )

preds =  LGBM_Model.predict(7)
```

**Comment by Allena101** [comment]
"The solution is to either increase output_chunk_length or change the lags so that the covariates extend far enough."

Is there any way to know/calculate how far you can predict (how many N) based on your lags?

**Comment by madtoinou** [comment]
You need to call `drop_after`, not `drop_before` if you want to shorten the target series on the "future" side.

It depends on the values of the lags and the time index end for each series (covariates included) as well as the value of `multi_models`. Assuming lags on the target and past covariates, you can get the last "forecastable" time by iteratively:
- target series : `fct_end = target_ts.time_index[-1] + output_chunk_length * target_ts.freq` (without auto-regression)
- past covariates : in order to perform auto-regression, you need to have enough "future" past covariates values to extract the lags one more time. So if `past_cov_ts.time_index[-1] > fct_end + max(lags_past_covariates)` (lags are negative for past covariates), you should have enough values to do one round of auto-regression.

By repeating these two operations, you should be able to know how far the auto-regression can go in the future given the lags and covariates.

Adding an example to illustrate:
```python
from darts.models import LinearRegressionModel
import darts.utils.timeseries_generation as tg

ts = tg.gaussian_timeseries(length=20, column_name="dummy")

m = LinearRegressionModel(lags=5, lags_past_covariates=[-3, -2], output_chunk_length=1)
ts_target = ts
ts_pc = ts[:17] # ts[:18] would also fail
m.fit(series=ts_target, past_covariates=ts_pc)
# fails because past covariates series ends to early
m.predict(n=1) 

ts_pc = ts[:19]
# works, we can extract the values at -3, and -2 with respect to the first forecasted step (0 by convention)
m.predict(n=1, past_covariates=ts_pc) 

# now, let's say we want to forecast 2 values with the same model using auto-regression
# the fist forecast will give one value, we can say that len(ts_target) = 21 now
# adding 1 values to the past covariates, so that:
# - the -2 lag of the first forecast becomes the -3 lag of the auto-regression
# the added value is the lag -2 of the position forecasted with auto-regression.

ts_pc = ts[:20] 
# works
m.predict(n=2, past_covariates=ts_pc) 
```

**Comment by Allena101** [comment]
Thanks alot for the example and explanation madtoinou!

This will be very useful indeed :D

sorry, i forgot to close the issue before 🙏
