### ISSUE TITLE
is it possible to create an encoder for moving average so that it can be used as a future covariate? 

### ISSUE THREAD

**Issue by Allena101** [unit8co/darts#2262]
I know how to create moving averages features. I have relied on pandas but i know you can do it with your timeseries objects as well! 

I have not been able to figure out how to use the moving average as a future covariate. At least if you are predicting iteratively (sorry i forget the term), could you not then also just attach the moving average from lets say the last 3 predictions, and do that for as long as needed (i.e. N predictions)?

Perhaps you guys have already built this functionality. Maybe you are meant to create your own function use if with the encoder argument?

**Comment by madtoinou** [comment]
Hi @Allena101,

If I understand correctly, you are applying moving average on the target component and use it as a covariate? And now, you would like the model to automatically call this transformer on its own forecasts to be able to perform auto-regression for an arbitrary number of steps? Darts does not contain such feature at the moment.

The simplest approach would be to implement custom code, with a loop (see [example](https://github.com/unit8co/darts/issues/1742#issuecomment-1590566819)) and manually re-generate the moving average covariates.

I don't think that implementing such encoders using the framework provided by Darts will be easy since they are intended to manipulate the time indexes only and not the values themselves. Furthermore, the encodings are generally generated in "one-go", before forecasts, so without access to the values generated during the auto-regression.

**Comment by Allena101** [comment]
> Hi @Allena101,
> 
> If I understand correctly, you are applying moving average on the target component and use it as a covariate? And now, you would like the model to automatically call this transformer on its own forecasts to be able to perform auto-regression for an arbitrary number of steps? Darts does not contain such feature at the moment.
> 
> The simplest approach would be to implement custom code, with a loop (see [example](https://github.com/unit8co/darts/issues/1742#issuecomment-1590566819)) and manually re-generate the moving average covariates.
> 
> I don't think that implementing such encoders using the framework provided by Darts will be easy since they are intended to manipulate the time indexes only and not the values themselves. Furthermore, the encodings are generally generated in "one-go", before forecasts, so without access to the values generated during the auto-regression.

yes, that is exactly what i want to do, madtoinue!

I was thinking it might be possible by doing something like this:
def moving_average(idx ,moving_average_window,target_feature):
    values_to_be_averaged = series[target_feature].tail(moving_average_window)
    current_moving_average = (values_to_be_averaged / moving_average_window)
    return current_moving_average

encoders = {
    "moving_average": {"future": [moving_average]}
}

I read the loop example you linked. If you have more than one future covariate, wouldn't you need to concatonate those values to the training_ts (from your example)?

**Comment by madtoinou** [comment]
As mentioned in my previous message, the `encoders` receive the series index only and cannot access its values (making it impossible to apply a moving average). Also, the encodings are generated in one go (as a series covering all the necessary timesteps) at the beginning of `predict()` and cannot access the first forecasts of the model (when `n > output_chunk_length`). Because of all these reasons, the code snippet you shared cannot work.

In the example, `training_ts` is the target series;  it would not make sense to concatenate covariates (which are not forecasted) to this series. But if you are building the covariates based on the first forecasts of an auto-regression, then you would indeed need to concatenate the new values to the covariates series for the next round of this "manual" auto-regression (loop calling predict() with `n <= output_chunk_length` instead of relying on its internal loop).

**Comment by Allena101** [comment]
> As mentioned in my previous message, the `encoders` receive the series index only and cannot access its values (making it impossible to apply a moving average). Also, the encodings are generated in one go (as a series covering all the necessary timesteps) at the beginning of `predict()` and cannot access the first forecasts of the model (when `n > output_chunk_length`). Because of all these reasons, the code snippet you shared cannot work.
> 
> In the example, `training_ts` is the target series; it would not make sense to concatenate covariates (which are not forecasted) to this series. But if you are building the covariates based on the first forecasts of an auto-regression, then you would indeed need to concatenate the new values to the covariates series for the next round of this "manual" auto-regression (loop calling predict() with `n <= output_chunk_length` instead of relying on its internal loop).

Would this work (this is your example but I added the last line):

# number of values to predict with auto-regression
forecast_horizon=10
# original values, without the rolling mean
raw_values = ts.values()
# pre-allocate the time index
extended_time_index = pd.date_range(start=ts.start_time(), periods=len(ts)+forecast_horizon, freq=ts.freq)
# rolling mean applied
new_values = np.convolve(raw_values.flatten(), np.ones(3), 'valid')
training_ts=TimeSeries.from_times_and_values(times=extended_time_index[:len(new_values)],
                                             values=new_values)

# forecast_horizon is the number of values to predict
for i in range(forecast_horizon):
    prediction = model.predict(n=1, series=training_ts)
    # stack the values vertically
    raw_values = np.vstack([raw_values, prediction.values()])
    # apply the rolling mean on the array
    new_values = np.convolve(raw_values.flatten(), np.ones(3), 'valid')
    # create the new ts
    training_ts=TimeSeries.from_times_and_values(times=extended_time_index[:len(new_values)],
                                                 values=new_values)
    # assuming you have future_covariates of course that matches the prediction dateTime/index
    training_ts = training_ts.concatenate(future_covariates, axis=1)

I dont know if darts sorts out the index here automatically. You have designed darts to match date indexes in smart ways but i dont know if that works here.
