### ISSUE TITLE
Different CPU and GPU behaviour

### ISSUE THREAD

**Issue by soroosh-rz** [unit8co/darts#2285]
I am using TCN model on darts 0.27.1.
It shows a very different behaviour on GPU and CPU. On CPU after 5 epochs, it reaches very good results but on GPU after 300 epochs!
I wonder how I can make CPU and GPU behaviour compatible?

**Comment by madtoinou** [comment]
Hi @soroosh-rz,

As the implementation is not changing between CPU & GPU, this is probably caused by something else. Can you check if using the same seed for both yield the same result? Also, did you run this experiment in replicates to make sure that the CPU "acceleration" was consistently converging faster than GPU's?
