### ISSUE TITLE
Static covariates with past or future covariates

### ISSUE THREAD

**Issue by lamolivier** [unit8co/darts#2332]
Hi,

In my understandings, static covariates are only usable with target variables.
What do you suggest if I want to use static covariates with past/future covariates ?

As an example, I have historical and forecast weather data for multiple points. As I do not want to predict weather data, I am using historical weather data as past covariates and forecast weather data as future covariates. Static covariates could be the longitude / latitude of the points for which weather data is available. 

Is there a way to include longitude/latitude data in DARTS models ?

Thank you!

**Comment by madtoinou** [comment]
Hi @lamolivier,

Why don't you want to encode the longitude/latitude in the static covariates of the target?

**Comment by lamolivier** [comment]
Hi @madtoinou,

From your question, I understand that you are suggesting to include weather data into targets ?

1) What about future covariates ? I am not sure that it makes sense to predict "already forecasted" data ?
2) It means that the model will lose the focus on predicting my "main" target variables as the model will be optimised on the weather data too. This may add some regularisation but this is not desired.

**Comment by madtoinou** [comment]
I am not suggesting to add the weather as a target, rather to encode the location in the target.

Since the weather forecasts that you are including as covariates are supposed to correspond to the localization of your target (which is not supposed to change over time), you could encode them directly there? Furthermore, if you start using several series during training, your model will be capable for adapting its forecasts depending on the "target series" that you will be running inference for (thanks to static covariates associated with the series).

**Comment by lamolivier** [comment]
Okay, thank you very much for your input @madtoinou !!
