### ISSUE TITLE
Is there a way to train a forecasting model for a few epochs with one training length, and then increase the length for some further epochs?

### ISSUE THREAD

**Issue by chododom** [unit8co/darts#2345]
I would like to test training for example the RNN for the prediction of 4 time steps ahead, and after a while, increase the horizon to for example 8 steps. Can I change this behaviour of the model somehow?

**Comment by dennisbader** [comment]
Hi @chododom, internally RNN has an `output_chunk_length=1`, meaning during prediction when `n>output_chunk_length` it will always perform auto-regression (consuming it's own predictions for future predictions) to forecast `n` points.

`training_length` just means how of those auto-regressive predictions it performs for one sample during training.

You can do two things:
- simply increase `n` from 4 to 8 when calling `predict()`
- multiple training:
  - train a `model1` with the lower `training_length`
  - save the model with [`model1.save(...)`](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.rnn_model.html#darts.models.forecasting.rnn_model.RNNModel.save)
  - create a new `model2` object with the same hyperparameters but different `training_length`
  - load the weights from `model1` save into `model2` with [`model2.load_weights(...)`](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.rnn_model.html#darts.models.forecasting.rnn_model.RNNModel.load_weights) (since `training_length` changed, for this to work you need to set `skip_checks=True`, and `load_encoders=False`).
  - train `model2`

**Comment by adesso-dominik-chodounsky** [comment]
@dennisbader Thank you for the advice! Do you think this will also work with the TFT model? If I understand correctly, the TFT has a built-in prediction horizon length.

**Comment by dennisbader** [comment]
@adesso-dominik-chodounsky, any of Darts' torch models (neural networks) and regression models support auto-regressive predictions with `n>output_chunk_length`. The only requirement is that if you use `past/future_covariates`, you must know these far enough into the future to generate the `n` prediction points.
