### ISSUE TITLE
FFT 2d forecasting

### ISSUE THREAD

**Issue by AlexLazarovich** [unit8co/darts#2356]
Is it possible to use the FFT forecasting model with matrices, for example forecasting image continuation?

**Comment by madtoinou** [comment]
Hi @AlexLazarovich,

If you come up with a nice way to flatten (and then reshape back) your matrix/image into `TimeSeries` components, it should be possible? However, due to considerable dimensions increase, the training will definitely take much more time. Using `input_chunk_length>1` will allow you to intake several images in the past, and `output_chunk_length>1` to forecast several images into the future. The covariates could probably still be used.

I don't think that any of the model in Darts was implemented with such use-case in mind but I am very curious to see if you can make it work.
