### ISSUE TITLE
Embedding extraction for clustering

### ISSUE THREAD

**Issue by Vignesh-Sampat** [unit8co/darts#2397]
I have trained several MixedCovariatesTorchModel families for forecasting models. Is there a way to use only the encoder to extract embeddings from past covariates during inference?

**Comment by madtoinou** [comment]
Hi @Vignesh-Sampat,

This feature is not supported out of the box, you will need to implement some custom code to run inference only on the encoding part of the models and return the corresponding `Tensor`. Since they have different architectures, you will have to have something specific for each `MixedCovariatesTorchModel` sub-class.

Out of curiosity, why do you want/need to cluster the embedding of the past covariates series?
