### ISSUE TITLE
Does Darts support mixed-frequency data?

### ISSUE THREAD

**Issue by kkckk1110** [unit8co/darts#2451]
I have a dataset, in which the target time series is monthly recorded, while the covariates are daily recorded. In this, can I directly use the covariates to predict the target variable? I noticed that in 00-quickstart.ipynb, in the following codes, the past_covariates air_covs had both month and year records. But I still hope to check this issue. Thank you.

model = NBEATSModel(input_chunk_length=24, output_chunk_length=12, random_state=42)

model.fit(
    [train_air_scaled, train_milk_scaled],
    past_covariates=[air_covs, milk_covs],
    epochs=50,
    verbose=True,
);

**Comment by kkckk1110** [comment]
When I tried to achieve the purpose, I came across the following error:

ValueError: The dataset contains past covariates whose time axis doesn't allow to obtain the input (or output) chunk relative to the target series.

The past covariates are daily frequent while the target is monthly.

**Comment by madtoinou** [comment]
Hi @kkckk1110,

In the quick-start notebook, the two series have a monthly frequencies. However, if you are training your model with multiple target series, they don't need to all have the same frequencies. It's just important to make sure that each pair of target and covariates series have the same frequency (otherwise, it's not possible to "align them" and extract the lags).

In your case, you might want to use the [MIDAS method](https://unit8co.github.io/darts/generated_api/darts.dataprocessing.transformers.midas.html?highlight=midas#darts.dataprocessing.transformers.midas.MIDAS) to resample the past covariates.

Hope that it helps.
