### ISSUE TITLE
MAPE calculation error?

### ISSUE THREAD

**Issue by hiydavid** [unit8co/darts#248]
https://github.com/unit8co/darts/blob/df7287684018372c9a23e3ec66477e22ac543643/darts/metrics/metrics.py#L287

I think the MAPE calculation should be:
`return 100. * np.mean(np.abs(y_true - y_hat) / y_true)`

I've been using darts for a bit and found the MAPE to be inaccurate, and this might be the cause.

**Comment by hrzn** [comment]
Hi @hiydavid, I think our computation is correct - see: https://en.wikipedia.org/wiki/Mean_absolute_percentage_error
the absolute value should be taken over everything within the summation.

Do you have more informations about how the MAPE was inaccurate in your case?

**Comment by hiydavid** [comment]
I'm seeing conflicting information on the internet.... here's several places showing taking absolute value for only the error and not the whole thing:

- https://stats.stackexchange.com/questions/299712/what-are-the-shortcomings-of-the-mean-absolute-percentage-error-mape
- https://ibf.org/knowledge/glossary/mape-mean-absolute-percentage-error-174
- https://www.gestiondeoperaciones.net/proyeccion-de-demanda/error-porcentual-absoluto-medio-mape-en-un-pronostico-de-demanda/

I've always done it the other way, but i guess it actually doesn't matter since the order doesn't impact the outcome. The reason why i first thought there's an issue is because I was using darts to create a backtest and used both MAPE and MAE to compare accuracy. I found that in some instance MAPE and MAE contradicted each other and saw that the MAPE I got didn't make sense.

**Comment by hrzn** [comment]
I guess some people are formulating it without taking the absolute value of the denominator because they implicitly assume positive time series. In this case the two variants are the same. However I think that in the general case the wikipedia version is correct. See also this (reliable) reference: https://otexts.com/fpp2/accuracy.html

It's expected that MAPE and MAE could contradict each other in some cases. Also bear in mind MAPE is not recommended for intermittent time series (with zero or near-zero values), as it becomes unstable.

**Comment by lrbachtiar** [comment]
Just chiming in on this closed issue since I also encountered it.
@hrzn  @hiydavid , here is an example:
```        
        date    y_true    y_pred  option_1  option_2
0 2021-11-19  0.112445  1.057871  8.407868  8.407868
1 2021-11-20 -0.313198  1.061737 -4.389988  4.389988
2 2021-11-21 -0.197375  1.065602 -6.398861  6.398861
3 2021-11-22  0.177551  1.069468  5.023451  5.023451
4 2021-11-23 -0.125248  1.073333 -9.569658  9.569658
```

Which produce these different MAPE values:
```
option_1   -138.54%
option_2    675.79%
```

Where:
* option_1: `100. * np.mean(np.abs(y_true - y_hat) / y_true)`
* option_2: `100. * np.mean(np.abs((y_true - y_hat) / y_true))`

I can see why there would be confusion because looking at y_true and y_pred plots that are near-zero, you may think the MAPE value would not be too high. But since MAPE accounts for the **absolute** error, the net differences are ignored and contribute equally to the final error.
