### ISSUE TITLE
[BUG]Can't run example methods in M4_competition_benchmark.ipy

### ISSUE THREAD

**Issue by chenghaoliu89** [unit8co/darts#249]
**Describe the bug**
For ses method, it raises error 
![image](https://user-images.githubusercontent.com/74166079/102714869-98f82580-430c-11eb-8a72-c7a13d71bb74.png)
For holt method, it raises error
![image](https://user-images.githubusercontent.com/74166079/102714889-b6c58a80-430c-11eb-9b1e-b51ef3596fc2.png)
For damp method, it raises error
![image](https://user-images.githubusercontent.com/74166079/102714898-cb098780-430c-11eb-88b4-0aa949a5e680.png)
The current results of append_values function in `seasonOut = seasonOut.append_values(seasonOut.values())[:len(test)]` is like
![image](https://user-images.githubusercontent.com/74166079/102714958-1de33f00-430d-11eb-8b4c-613886a256ef.png)
,which brings error in  `naive2.predict(len(test)) * seasonOut`

Besides, when I run evaluate_ensembling.py, it raises error
![image](https://user-images.githubusercontent.com/74166079/102715238-fe4d1600-430e-11eb-92ca-5114c34f8c91.png)

**To Reproduce**
run M4_competition_benchmark.ipynb
run evaluate_ensembling.py

**System (please complete the following information):**
 - Python version: 3.8.5
 - darts version [e.g. 0.5.0]

**Comment by pennfranc** [comment]
Thanks for letting us know! The problem is that this example code was written using an older version of darts and has not been updated since. The specific error you experienced is due to the fact that we transitioned from string-type to Enum-type parameters in these models. Instead of darts 0.5.0 try using darts 0.2.2 instead.
That being said, we should definitely make this clearer, either adding a disclaimer or removing this example code. Thoughts @hrzn @TheMP ?

**Comment by hrzn** [comment]
We have removed these scripts as they were outdated. We'll come up with better examples in the future.
