### ISSUE TITLE
[Question] window_agg parameter not clear in anomaly scorers

### ISSUE THREAD

**Issue by slavakx** [unit8co/darts#2498]
I am referring to the [Anomaly Detection Example](https://unit8co.github.io/darts/examples/22-anomaly-detection-examples.html) tutorial and the explanation of the anomaly scorers

> The window_agg can be used to transform the window-wise scores into point-wise scores by aggregating all anomaly scores from each window that the point was included in`

Can somebody please explain the logic behind, what does it mean _to transform the window-wise scores into a point-wise scores_ and consequences of both approaches. 

In the tutorial both options for window_agg were used but no further distinction was made during the evaluation
`WassersteinScorer(window=half_a_day, window_agg=False)`
 `WassersteinScorer(window=full_day, window_agg=True)
`

**Comment by madtoinou** [comment]
Hi @slavakx,

You are sometimes interested to know if an anomaly occurred in a window of time (instead of trying to detect them point-wise): this argument allows to "aggregate" the scores within a window and assign this new score to a specific timestep, making the model less sensible to outliers for example.

I hope that it makes things clear!
