### ISSUE TITLE
Question of validation data length and how samples are extracted from the validation dataset

### ISSUE THREAD

**Issue by unit1111** [unit8co/darts#2501]
I’m trying to understand how samples are extracted from the validation dataset, particularly for the N-BEATS model, as described on this page:

https://unit8co.github.io/darts/userguide/torch_forecasting_models.html#training-with-a-validation-dataset

```python
# create train and validation sets
ice_cream_sales_train, ice_cream_sales_val = ice_cream_sales.split_after(training_cutoff)

# train with validation set
model.fit(series=ice_cream_sales_train,
          past_covariates=temperature,
          future_covariates=weekday,
          val_series=ice_cream_sales_val,
          val_past_covariates=temperature,
          val_future_covariates=weekday)
```
The page mentions that both the training and validation datasets must meet the minimum length requirements, ensuring that at least one sample with an input and output chunk can be extracted from the data provided. In terms of the minimum required time spans, this means:
* The target series must have a minimum length of input_chunk_length + output_chunk_length.

Assuming my input_chunk_length is 7 and output_chunk_length is 1, if I choose a training_cutoff that results in the validation data having a length of 7+1, will only one sample be extracted from the validation dataset? Or will Darts utilize the last input_chunk_length steps of data from the training set to extract more samples, since the training and validation data are sequential?

Additionally, do you have any recommendations on the minimum number of samples required for training and validation to effectively run an N-BEATS model? I have a very small time series dataset and would like to know if it’s feasible to run such a complex model.

**Comment by madtoinou** [comment]
Hi @unit1111,

Your assumption is correct; if the validation data as a length of 8, it will result in only one validation sample: 7 timestamps for the input (`=input_chunk_length`) and 1 timestamp for the target (`=output_chunk_length`). There is no fancy logic to try to use the end of the training data in the validation because the two sets could be completely separate (and not necessarily sequential). But you could eventually manually adding `output_chunk_length` steps of the training set to the validation if you want (but it'll cause data leakage if you had more, as it would start to include timestamps that were effectively forecasted during training).

It's difficult to tell, it also depends on the complexity of your data and which parameters you use for the model architecture. Maybe start with regression models and if they do a good job, you might not need to use deep learning.

I hope that it helps.
