### ISSUE TITLE
[QUESTION] How to make prediction with XGBModel when trained on multiple time series?

### ISSUE THREAD

**Issue by dangk01** [unit8co/darts#2521]
I am training a generalized model for a physical experiment. I have a Pandas dataframe containing multiple IDs (experiment ID). Each ID has the same 1000 time steps (1,...,1000), along with numeric 5 features, and 1 target.
My goal is to create a model that takes a new time series with only 5 features in 1000 time steps with unknown target column to predict it.

I am not sure how to set it up correctly. My attempt so far is below:

```
target_series = TimeSeries.from_group_dataframe(df, group_cols='id', time_cols='Time', value_cols="Target_value")
covariates_series = TimeSeries.from_group_dataframe(df, group_cols='id', time_cols='Time', value_cols=features)

model = XGBModel(lags=10, lags_past_covariates=10, use_static_covariates=False, out_put_chunk_length=2000)
model.fit(target_series, past_covariates=covariates_series )

new_covariates = TimeSeries.from_dataframe(new_df, group_cols='id', time_cols='Time', value_cols=features)
pred = model.predict(n=1000, series = None, past_covariates=new_covariates)

```

Errors are: 
- series needs to be provided. But I can only provide the Time. From the example, it seems one way to work around is to pass series of a specific Experiment ID and let the model forecast from t=1001, but for my case, IDs are just unique values to order the experiments.

Thank you in advance.

**Comment by madtoinou** [comment]
Hi @dangk01,

If a model is fitted on several series, you need to specify which series needs to be and forecasted (since there is an ambiguity).

From what you are describing, it appears that you don't have the target values for the product IDs to predict. Since these features are not available at inference time, it means that you model should not have lags on the target but only on the covariates (see [Covariate only forecasting](https://unit8co.github.io/darts/examples/20-RegressionModel-examples.html#Covariates-based-forecasting)). The model should be defined as:

```python
# lags=None is the key
model = XGBModel(lags=None, lags_past_covariates=10, use_static_covariates=False, output_chunk_length=1000)
# create a dummy series with a time index finishing just before the period to be forecasted
model.predict(series=Timeseries.from_times_and_values(times=covariates_ts[-1:], values=[0]))
```

This should to the trick, note that having a `output_chunk_length` much greater than the number of features (lags) is likely to cause poor performance. I would recommend checking the [Quickstart](https://unit8co.github.io/darts/quickstart/00-quickstart.html) and [RegressionModel](https://unit8co.github.io/darts/examples/20-RegressionModel-examples.html) notebooks to familiarize yourself with all the features.
