### ISSUE TITLE
How does DARTS deal with missing values?

### ISSUE THREAD

**Issue by ETTAN93** [unit8co/darts#2528]
How well does Darts deal with timeseries forecasting when there are missing values.

Assuming I am using a LGBM model within the DARTS framework, is the suggested solution to:
i. Leave the missing values as NaN because LGBM can deal with missing values by itself by splitting the trees accordingly.
ii. Fill in missing values so that there is a continuous timeseries and create a column with a separate 0,1 flag to mark those rows that are filled in.

Not sure if this relates to Darts in anyway or is it just depending on the model architecture used?

**Comment by dennisbader** [comment]
Hi @ETTAN93, as you say it is more of a modelling question rather than Darts specific.

I would for sure try out the different approaches and see what yields the best results:
- filling missing values and adding a flag also adds more features / model complexity (also depends on which lags you use for that flag)
- if you only have missing values in your training set, you can also try ignoring times with missing values through the sample weights (as described [here](https://unit8co.github.io/darts/quickstart/00-quickstart.html#Sample-Weights))
