### ISSUE TITLE
[QUESTION] indices of groups when using TimeSeries.from_group_dataframe

### ISSUE THREAD

**Issue by marcoscattolin** [unit8co/darts#2616]
**Describe the issue linked to the documentation**

I am using `TimeSeries.from_group_dataframe` to create timeseries for weekly sales of some items.  Series should be grouped by `'item_id'`, with items sharing potentially useful covariates (eg `'item_category'`)

I am not sure how to handle indices of timeseries. More specifically, when creating series via `TimeSeries.from_group_dataframe`:

- if I specify `drop_group_cols=['item_id']`, then item_id is removed from static covariates. However I don't know how to map elements in the list of series to their `item_id`'s

- if I do NOT specify `drop_group_cols`, then item_id is added to static_covariates. However using this as a covariate is not useful - sometimes even detrimental - for downstream models

Please consider in my pipeline I am also removing series from the created list depending on some conditions, so I believe there should be a a way to handle grouping indices separately from static_covariates.

Thanks,
Marco

**Comment by madtoinou** [comment]
Hi @marcoscattolin,

Why don't you keep `drop_group_cols=None` when calling `TimeSeries.from_group_dataframe` so that you still have this information available and remove the `item_id` at the end of your pipeline, just before training the model or just when you don't need them anymore;

```python
series = [ts.with_static_covariates(ts.static_covariates.drop("item_id")) for ts in series]
```

We are considering adding a meta-data attributes to series (tracked by #1794) but not sure yet of what is the best way to do it.

**Comment by marcoscattolin** [comment]
Thanks @madtoinou, that's probably the easiest way while you figure out how to add meta-data (personally I am strongly in favor of this).

Maybe one other option could be adding to models and transformers the possibility to exclude a list of static covariates
