### ISSUE TITLE
[BUG] TimeSeries type won't take a datetime.date for its time_col value

### ISSUE THREAD

**Issue by cmpunches** [unit8co/darts#2632]
**Describe the bug**
TimeSeries objects being converted from Pandas Dataframes will not accept a datetime.date column for the time_col value.  This indicates that TimeSeries was not intended for a daily period time series.

**To Reproduce**
```
    def to_timeseries(self, data, time_col='ds'):
        """
        Convert input data to a Darts TimeSeries.

        :param data: Either a TimeSeries object or a pandas DataFrame
                     with columns [time_col, value_col].
        :param time_col: Name of the timestamp column in the DataFrame.
        :param value_col: Name of the values column in the DataFrame.
        :return: TimeSeries
        """

        if isinstance( data, TimeSeries ):
            return data
        elif isinstance( data, pd.DataFrame ):
            data.reset_index(drop=False, inplace=True)
            # prophet uses pandas dataframes, but for whatever reason we're being forced to use Darts TimeSeries for
            # prophet if we want model flexibility which will require a refactor of the entire codebase
            time_col = 'ds' if 'ds' in data.columns else 'date' if 'date' in data.columns else None
            if time_col is None:
                raise ValueError("DataFrame must have either a 'ds' or 'date' column.")

            return TimeSeries.from_dataframe(
                df=data,
                time_col=time_col
            )
        else:
            raise TypeError(
                "Unsupported input type: {0}. Expected a Darts TimeSeries or a pandas DataFrame."
                .format(type(data))
            )
 ```

results in the following exception:

```
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'datetime.date'
python-BaseException
```

**Expected behavior**
Working with time series that support daily periodicity.  It's unclear why we're not or what was expected for time series values that occurred once daily.

**System (please complete the following information):**
 - Python version:  3.12.5
 - darts version: 0.32.0

**Additional context**
It would also be great if there were an option that just allowed us to use pandas dataframes.  There is zero benefit to a forced conversion and it is forcing alot of code to be rewritten.

**Comment by cmpunches** [comment]
After further testing, it's apparent that this library-specific TimeSeries object:

- is required to be used even for models darts wraps that prefer pandas dataframes
- lacks IDE support for viewing its structure and contents, to the point of it being difficult to validate alignment issues or successful conversions when working with the object
- prevents non-contiguous days in the dataset, such as trading days, which is actually breaking native functionality of models like prophet, which dart is wrapping
- won't allow "date" types for the index (as reported here)

I apologize in advance as I won't be able to help much on this bug report after it's initial filing, because I'm forced to drop darts from the project I'm working on due to the requirement to use this TimeSeries class.  I won't work with it, and I suspect I'm saving alot of work this way.

Either way, please feel free to either close this ticket or keep it open to potentially improve this class for others -- it's obvious some people have found a way to get it working for them, and don't feel singled out -- Pandas dataframes are pretty awful too.

**Comment by dennisbader** [comment]
Hi @cmpunches, regarding your first question:
- your TimeSeries can either be indexed with a `pd.DatetimeIndex` or a regular integer Index. In that case you won't have to supply `time_col`.
- if the time index is in the columsn (`time_col`), the column must either be `str`, numpy `datetime` or `int` dtype.
- we support special frequencies such as business days, as long as it is a well-defined pandas frequency (see [here](https://pandas.pydata.org/docs/user_guide/timeseries.html#offset-aliases)).
- `TimeSeries` use `xarray` under the hood. You can always convert it back to xarray, numpy array, or pandas DataFrame / Series using the corresponding methods. Then you can further investigate the data.

Why do we require your data to be converted to `TimeSeries`?
- Darts is a framework for providing a unified API to use dozens of different forecasting approaches (not only Prophet), time series processing, and anomaly detection.
- Having the `TimeSeries` allows us:
  - to verify your data and help you avoid a lot of pitfalls down the road by checking crucial assumptions (no missing dates, valid frequencies, ...)
  - to simplify modelling since we have the guarantee that your data follows our requirements
  - to store data in 3 dimensions (time, columns, samples). The samples dimension allows us to store stochastic / probabilistic information per time step and column

Sorry to hear it's not convincing you. I'll close the issue.
