### ISSUE TITLE
Darts how to build Timeseries - ValueError: cannot reindex from a duplicate axis

### ISSUE THREAD

**Issue by venergiac** [unit8co/darts#282]
**Describe the bug**
I have two columns:

TIME, QUANTITY
value is allocated quarterly with missing value.

```
2006-01-01  13.0
2006-04-01   2.0
2007-0-01   3.0
2007-10-01  11.0
```

I want to build Timeseries

**To Reproduce**
```
_df.index = _df[TIME]

series = TimeSeries.from_dataframe(_df, 
                                   #time_col=TIME, 
                                   value_cols=[QUANTITY], 
                                   freq='Q',
                                   fill_missing_dates=True)

series = fill_missing_values(series=series, fill=0.0)
```

**Expected behavior**
I can solve using pandas interpolation, but I do not think is the right way.

```
_df.index = _df[c_time]
#_df = _df[c_quantity]
_df = _df.resample('Q').sum().interpolate(method='time')
```

**System (please complete the following information):**
 - Python version: 3.7
 - darts version: 0.6.1

**Comment by tneuer** [comment]
Thanks for reporting this to us. When I tried to reproduce your code I indeed got a wrong behaviour. 
But I think the problem lies in the specification of your freq="Q" parameter. Our time series objects are based on pandas and looking [here](https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#offset-aliases) you can see that "Q" means Quarterly End Data. You would need "QS" as Quarterly Start to get the expected behaviour. So using 
```python
series = TimeSeries.from_dataframe(_df, 
                                   value_cols=[QUANTITY], 
                                   freq='QS',
                                   fill_missing_dates=True)
```
should work.

As a quick sidenote: When reproducing your method using `interpolate` the time index of the result is off, exactly because pandas assumes it is quarterly end data format, which is not the expected behavior that I think you are looking for :)
