### ISSUE TITLE
Support in-sample fit in neural network based models, such as TransformerModel

### ISSUE THREAD

**Issue by jasonweiyi** [unit8co/darts#301]
It seems that neural network based models, such as TransformerModel, does not support in-sample fit. In other words, there is no way to know how a model trained with a time series over a time range managed to capture that time series over the same time range.

Is there a plan to support this? Thank you.

**Comment by hrzn** [comment]
Currently there's no plan to support this, because unlike other models it's not something that is natively computed when NNs are trained. If you would like to capture this you can do it manually quite easily though (just train your NN on a full series, and then backtest it on this series for example).
