### ISSUE TITLE
Can't apply Darts to yahoo finance data

### ISSUE THREAD

**Issue by ssantoshp** [unit8co/darts#303]
Hey, I have a problem. I tried to apply the `Darts` library to a dataset from yahoo finance but it gives me an error I don't understand. Here is my code : 

`df = pd.read_csv('AMD.csv', delimiter=",")`
`series = TimeSeries.from_dataframe(df, 'Date', 'Close')`

The error given is:
`ValueError: Could not infer explicit frequency. Observed frequencies: {'D', 'B'}. Is Series too short (n=2)?`

Here is the full error: https://i.ibb.co/VVdCWrr/Capture.jpg

Can you help me because I don't understand what is the problem?

You can find the dataset (AMD.csv) here: https://finance.yahoo.com/quote/AMD/history?p=AMD

**Comment by hrzn** [comment]
That's because Darts could not infer the frequency of the `TimeSeries`, because your data contains some missing dates. You should try specifying the `freq` parameter:
```
series = TimeSeries.from_dataframe(df, 'Date', 'Close', freq='D')
```
This series will have missing dates though (because your data has missing dates). Depending on what you want to do with it, you might want to interpolate the values in between, which would look like this:
```
from darts.utils.missing_values import fill_missing_values
series = fille_missing_values(series)
```
