### ISSUE TITLE
Can autoarima forecast under a confidence level? Thanks.

### ISSUE THREAD

**Issue by jerpson** [unit8co/darts#351]
**Is your feature request related to a current problem? Please describe.**
A clear and concise description of what the problem is.

**Describe proposed solution**
A clear and concise description of what the library should provide to solve missing functionality.

**Describe potential alternatives**
A clear and concise description of any alternative solutions or existing features that might solve it.

**Additional context**

**Comment by pennfranc** [comment]
Hi @jerpson, I think you're asking about whether you can produce confidence intervals as part of a prediction on top of point predictions, correct? Currently Darts does not support confidence intervals. However, we are planning to introduce this functionality as part of a big update where we will introduce probabilistic forecasting models. I am not yet sure whether this will include `AutoARIMA`, since we are wrapping a model from a different library, which as far as I can tell does not provide this functionality out of the box. But please stay tuned for our next updates!

**Comment by hrzn** [comment]
Hi @jerpson starting in v0.9.0 the model `ARIMA` is probabilistic - you just have to provide a `num_samples` argument to `predict()` in order to get back a probabilistic `TimeSeries` (for instance: `model.predict(n=36, num_samples=1000)`, from which you can obtain quantiles for instance, by calling `quantiles_df()` or `quantile_timeseries()`. 

`AutoARIMA` is not (yet) probabilistic, but once you have figured out the best ARIMA parameters using `AutoARIMA`, you can fit a probabilistic `ARIMA` model.
