### ISSUE TITLE
[BUG] prophet instead of fbprophet

### ISSUE THREAD

**Issue by pablodz** [unit8co/darts#355]
**Describe the bug**
Error during install via pip on linux

**To Reproduce**
1. pip3 install darts

**System (please complete the following information):**
 - Python version: 3.9.5
 - darts version 0.8.1

New package for `fbprophet` is just `prophet` (via pip)
https://github.com/facebook/prophet

Error log: 

https://pastebin.com/9pH6gt4g

**Comment by pennfranc** [comment]
Hey @pablodz, currently we're suggesting to run `conda install -c conda-forge -c pytorch pip fbprophet pytorch cpuonly` on a fresh conda environment before installing darts. Does that work for you?

**Comment by akanz1** [comment]
@pennfranc Thank you, this works, at least on the second attempt. I had another error regarding tqdm (see below) using this approach.

`ERROR: Could not install packages due to an OSError: [WinError 5] Permission denied: 'C:\\Users\\username\\AppData\\Local\\Temp\\pip-uninstall-mo_hidfk\\tqdm.exe'
Consider using the `--user` option or check the permissions.`

I've used your command, then pip install darts (that's when the error showed up) and after giving `pip install darts` another try it ran just fine.

**Comment by pennfranc** [comment]
@akanz1 Thanks for reporting! Anyways, I'm glad it works now. If you encounter this problem again feel free to open an issue on GitHub.
