### ISSUE TITLE
Question: Why the output length must be smaller than input length in TCN

### ISSUE THREAD

**Issue by vpozdnyakov** [unit8co/darts#367]
There is a constraint in TCN implementation https://github.com/unit8co/darts/blob/master/darts/models/tcn_model.py

```python
raise_if_not(output_chunk_length < input_chunk_length,
    "The output length must be strictly smaller than the input length", logger)
```

Could you please explain why this restriction is applied? Input and output sequences have the same length in the original paper https://arxiv.org/pdf/1803.01271.pdf

<img src=https://user-images.githubusercontent.com/12996098/124521409-0e829980-ddf8-11eb-85c5-ee2aa9fabc67.png width=400>

**Comment by pennfranc** [comment]
You are absolutely right in that the length of the output tensor of the TCN architecture is the same as the length of the input tensor. The thing is, we mean something different here with the term 'output_chunk_length'. Since we use the TCN model in the context of forecasting, with 'output_chunk_length' we mean the length of the output tensor that actually corresponds to forecasts. Or in other words, it corresponds to how many steps the targets in the training set are shifted with respect to the inputs. So the reason why this value cannot be larger than 'input_chunk_length' is precisely because the length of the output tensor is the same as the input tensor, and at most we can predict as many points into the future as the output tensor is long. At least with our current architecture. You can find a more detailed explanation here: https://medium.com/unit8-machine-learning-publication/temporal-convolutional-networks-and-forecasting-5ce1b6e97ce4.

However, I don't remember why we require the strict inequality to hold, maybe that's not even necessary. I will look into it soon. In the meantime, feel free to ask more questions if things are not clear!

**Comment by vpozdnyakov** [comment]
Thanks for a comment! I thinks it can be relaxed to `output_chunk_length <= input_chunk_length`. For example it can be applied in a case of sequence-to-sequence modeling where sequences are not overlapped, say to predict [y_11, ..., y_20] using [y_1, ..., y_10]. Also it would be great to fix a link to an example notebook in your blogpost (the link in "TCN examples notebook" in the section "Example").

**Comment by pennfranc** [comment]
You're probably right about the requirement. Also thanks for the suggestion, I will add the link to the notebook!
