### ISSUE TITLE
Covariate series for Prophet

### ISSUE THREAD

**Issue by trungtly** [unit8co/darts#461]
**Is your feature request related to a current problem? Please describe.**
`prophet` supports external regressor, but `darts` does not implement this feature

**Describe proposed solution**
`prophet` adds external regressor as in [their documentation](https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#additional-regressors)

Can `darts` support this with past / future covariate series ?

**Describe potential alternatives**
A clear and concise description of any alternative solutions or existing features that might solve it.

**Additional context**

**Comment by hrzn** [comment]
Yes this is a good point, thanks for raising, we'll see if there's a way to do this in a clean way.

**Comment by dennisbader** [comment]
Hi @trungtly and thanks for the request.
We are currently working on adding covariate support for prophet with darts!

**Comment by dennisbader** [comment]
@trungtly adding covariates will be supported after merging #495 .
You can then add covariates with:
`model.fit(train, future_covariates=train_covariates)` and
`model.predict(n=len(test), num_sample=1, future_covariates=test_covariates)`.

Covariates are added as an extra regressor to the Prophet model, which is why they must be given for the fitting and prediction process.
This means that the covariates have to be known for the past and the forecast horizon you want to predict.

**Comment by trungtly** [comment]
Great, many thanks Dennis.
