### ISSUE TITLE
[BUG]forward method in BlockRNNModel passes hidden state to final layer

### ISSUE THREAD

**Issue by bingblackbean** [unit8co/darts#546]
**Describe the bug**
Thanks for this fantastic and handy package, it boosts timeseries forecasting.  I just want to clarify the code in BlockRNN Models. As the picture below, which is screenshot of forward method. Why hidden state is passed to next final layer rather than output in Line 108? ![image](https://user-images.githubusercontent.com/42602614/141527244-532c76b0-40aa-4b91-a69c-ea3cdd462da4.png)

**To Reproduce**
Just refer to the code.

**Expected behavior**
As I understand, out shall be passed to final layer rather than hidden state.

**System (please complete the following information):**
 - Python version: [e.g. 3.7]
 - darts version [e.g. 0.5.0]

**Additional context**

please close this thread, as I realize the code is correct

**Comment by pennfranc** [comment]
Hi @bingblackbean, thanks for your question. I can see how it might be a bit confusing that we're completely disregarding the output values of the RNN module and instead only make use of the hidden state. 
The idea behind this model is that it is a type of Sequence-to-Sequence model:
![1*1JcHGUU7rFgtXC_mydUA_Q](https://user-images.githubusercontent.com/42946363/142416509-4df74692-8b88-422f-8728-b6ac694c3804.jpeg) (source: https://towardsdatascience.com/understanding-encoder-decoder-sequence-to-sequence-model-679e04af4346)
So the whole point of the RNN module here is to serve as an encoder, that is to encode the input time series as one final hidden state vector, which is then taken as input to the decoder. Please note that, unlike in the image I included, our decoder is a FC neural network instead of another RNN. In other words, the 'output' of the RNN module in 'BlockRNNModel' is completely unused. The only reason why it appears at all is because the pre-made PyTorch RNN module includes it, but we don't need it.
I hope this helps. If not, please let me know!

**Comment by bingblackbean** [comment]
hi @pennfranc ,Thanks for the detailed explanation..

If I understand LSTM cell structure correctly, e.g. pic in below, the last output equals to last hidden state.
So it means, both  ` prediction = out[:,-1,:] `and    `prediction = h[-1, :, :] ` shall work.
![image](https://user-images.githubusercontent.com/42602614/142451153-6aa73653-c11b-4917-b18e-a77990fd5eb3.png)
