### ISSUE TITLE
Requirements for past & future covariates in validation set?

### ISSUE THREAD

**Issue by alexkyllo** [unit8co/darts#567]
Hello,

I've been going through the examples and trying to adapt TFTModel and a few of the other neural network models to my own dataset, which has multiple time series with past and future covariates. I'm using a validation set in the training because I want to track validation loss and use it to choose the best model.

My dataset is weekly for 196 weeks. I'm using `input_chunk_length=8`, `output_chunk_length=4` and my validation set is the last 39 weeks of the series. When I split my series and past and future covariates into a training set and a validation set, I get this error from `fit()`:

```
ValueError: The dataset contains some covariates that don't extend far enough into the future. (0-th sample)
```

And this error from `predict()`:

```
ValueError: When forecasting future values for a horizon n with models requiring past covariates, 
the past covariates need to be known (n - output_chunk_length) in advance
 (needed to produce forecasts when n > output_chunk_length). 
For the dataset's 0-th sample, the last covariate timestamp is 2021-09-27 00:00:00
 whereas it should be 2022-10-25 00:00:00.
```

It's not obvious to me, from the error messages, examples, or documentation, how to fix this, and I would greatly appreciate any advice.

**Comment by dennisbader** [comment]
Hi @alexkyllo and thanks for writing.

This error is raised when one of your covariate series doesn't cover a sufficient time span. Currently it ends at timestamp `2021-09-27 00:00:00`. For training to work, it needs all additional time steps until (and including) `2022-10-25 00:00:00`.

This probably comes from covariates on your validation set. We are currently working on a tutorial on covariates (it's still in draft state with spelling mistakes). Could you read [sections 3.1.1 and 3.1.2](https://github.com/unit8co/darts/blob/docs/cov-update/COVARIATES.md#311-requirements-for-training-with-past-and-future-covariates) and tell us if this makes it more clear? Let me know if not, and I'll explain further.

For section 3.1.1.: `TFTModel` is a `Mixed` covariate model.

**Comment by alexkyllo** [comment]
Thanks for the quick response!

This is helpful, but I think part of my problem was that I tried to also call `.split_after()` on the covariates, to create separate covariates series for validation, which is apparently unnecessary, and was somehow causing the error.

This example shows passing the same arguments to both `past_covariates` / `future_covariates` and `val_past_covariates` / `val_future_covariates`. I guess I don't understand why there are separate `val` arguments at all.

```python
# create train and validation sets
past_ice_cream_sales_train, past_ice_cream_sales_val = past_ice_cream_sales.split_after(training_cutoff)

# train with validation set
model.fit(series=past_ice_cream_sales_train,
          past_covariates=measured_past_temperature, 
          future_covariates=estimated_future_temperature,
          val_series=past_ice_cream_sales_val,
          val_past_covariates=measured_past_temperature,
          val_future_covariates=estimated_future_temperature)
```
I also feel like the `predict()` method is under-documented, considering how important it is, and the implicit assumptions it contains about `n`, `input_chunk_length`, `output_chunk_length`, and the prediction point.

![image](https://user-images.githubusercontent.com/2609312/143480244-ea21af0f-04f9-4bda-8773-01574cf941ad.png)

For example, I'm still not too clear on how to `predict` and score the model on a validation set.

Say I have a validation set consisting of the last 12 weeks of the weekly series, and I have the same 12 weeks of both past covariates and future covariates. My `input_chunk_length = 8`, `output_chunk_length = 4`, and `n=4`, so I want the prediction point to be after the 8th week of the validation set, and I want the model to use the first 8 weeks to predict the last 4 weeks of the validation set, and then calculate the validation loss and metrics such as MAPE, etc. How would I call `predict()` correctly to achieve this?

**Comment by dennisbader** [comment]
- Concerning separate `val` arguments: a new `TrainingDataset` instance is created for the validation set which is why these arguments are required. With this you could theoretically use a validation set that lies far ahead in the future (or past) compared to your training data without having to create an extensively long covariate series that covers all non-required steps in between.
- concerning `predict()`: Is this is the documentation from `TFTModel`? You are right, this unintentionally shadows the actual `predict()` doc of the parent class. Have a look at the RNNModel's documentation from [here](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.rnn_model.html#darts.models.forecasting.rnn_model.RNNModel.predict). This is how it should look like.

For your last question:
- If you pass the validation set that you describe to `model.fit()` then the model evaluates the metric on the validation set exactly as you want during training. 
If your validation set was longer than 12 weeks, it would autoregressively go through chunks of length `input_chunk_length + output_chunk_length` and evaluate the metric on each of those chunks until all data in the validation was covered.
- if you want the actual prediction with `predict()` to start at these last 4 weeks, make sure that the `train_series` you pass to `model.fit()` ends exactly one week before before these 4 last weeks. 
To predict the next 4 weeks set `n=4`. Your validation set can stay as it is.

**Comment by alexkyllo** [comment]
Thank you, this explanation is very helpful. Closing the issue.
