### ISSUE TITLE
TimeSeries.from_dataframe: ValueError

### ISSUE THREAD

**Issue by beergil** [unit8co/darts#950]
**Describe the bug**
ValueError: The time index of the provided DataArray is missing the freq attribute, and the frequency could not be directly inferred. This probably comes from inconsistent date frequencies with missing dates. If you know the actual frequency, try setting `fill_missing_dates=True, freq=actual_frequency`. If not, try setting `fill_missing_dates=True, freq=None` to see if a frequency can be inferred.

**To Reproduce**
series = TimeSeries.from_dataframe(df, 'D Onset', 'Total')

**Expected behavior**
Create a TimeSeries, specifying the time and value columns

**System (please complete the following information):**
 - Python version: Python 3.7.13

**Comment by YannickLehr** [comment]
As the error message already states, your data frame has no frequency set, nor can it be inferred.
I assume that is the problem since you don't give any further information regarding your data frame.

Try to resample your data frame with your desired frequency.

e.g if you want to have a daily aggregation:
`df_daily = df.resample('H').sum()`
 Furthermore you can set the frequency like this:
 `df_daily = df_daily('H')`
