### ISSUE TITLE
[BUG] black is using 80 line length

### ISSUE THREAD

**Issue by gdevos010** [unit8co/darts#967]
**Describe the bug**
flake8 has 120 line length but black's default is 
black needs this line added to it `args: ["--line-length", "120"]`
https://github.com/unit8co/darts/blob/155c653a5243af3dd56faad9ffa539bd58c8e050/.pre-commit-config.yaml#L1-L6

It also should be added here 
https://github.com/unit8co/darts/blob/155c653a5243af3dd56faad9ffa539bd58c8e050/build.gradle#L100-L103

@tomasvanpottelbergh Would you be able to add this? I feel like I didn't grasp the two commit setup

**Comment by tomasvanpottelbergh** [comment]
Sorry for the late response @gdevos010. Is this actually an issue? Black uses a line length of 88 by default, which we like. We set 120 for flake8 since a lot of our docstrings are that length, and it would take a lot of effort to fix that. Unless you are interested in doing that, we propose to keep the settings as they currently are.

**Comment by gdevos010** [comment]
We settled on 120 to match PyTorch when we first added the pre-commit code so I opened the big report. We can leave it at 88 if you prefer.

https://github.com/unit8co/darts/issues/739#issuecomment-1016370204

**Comment by tomasvanpottelbergh** [comment]
I think we're fine with 120 for the docstrings, while letting black enforce 88 for the code. Let's leave it like this for now and potentially change it when someone finds a good autoformatter for docstrings.
