### ISSUE TITLE
Frequency Offset Aliases - Future proofing for the unknown

### ISSUE THREAD

**Issue by martinb-bb** [unit8co/darts#980]
Hi! 

As you may know, tickers off of yfinance are structured as so: 
`YYYY-MM-DD` --> `2019-07-08`
Figuring out frequency for this would be business days : `B`

```python
ticker_series = TimeSeries.from_dataframe(
        data,
        time_col="date",
        value_cols=["Close"],
        freq="B",
        fill_missing_dates=True,
    )
```

But what if a user were to upload a timeseries that does not have inherent frequency as listed by pandas?: https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#offset-aliases

For instance: This timeseries seems to include Daylight Savings time. 
```
2021-11-04 04:00:00,60394613.0
2021-11-08 05:00:00,55020868.0
2021-11-08 05:00:00,55020868.0
2021-11-09 05:00:00,55020868..0
.
.
.
2022-11-04 04:00:00,60394453.0
```

8/10 times setting `freq=None` and `filling_missing_dates=True` does not work and cannot work out the frequency on new timeseries.  You can try to inspect seasonality but this does help as much as you would like. 

One could work around this by ignoring the datetime and using the index:
```python
ticker_series = TimeSeries.from_values(data["Close"].values)
```

But this removes the important element of time, especially when training `Global` models with covariants that are all different lengths and time stamps. Some of those covariates can be daily while others will be daily with minute-by-minute resolution. You want times to link up with each other.

I can also do some fancy string manipulation BUT that only works if I know what type of timestamping I will be working with.

So this brings up the bigger question: 

- What would the folks at Darts do in case they do not know the offset Alias BUT have timestamps that are important in providing insight to the data that is being processed especially for global models. Timeseries freq can be ms/sec/min/hour/day/every-other_day/every_third_day/every_N_days/quarter/year/every_N_unit/ etc. 
- Is there something I am completely overlooking that will sort this all out automatically? 😄

**Comment by martinb-bb** [comment]
Update: the only other thing I thought of was converting all incoming timeseries to a unix timestamp in unit of seconds. 

```python
new_date = (pd.Timestamp('2021-11-08 05:00:00') - pd.Timestamp("1970-01-01"))
```

That way, no matter what time series, all dates are still unique and now I can just forecast based on these unique indexes.

**Comment by hrzn** [comment]
Hi @martinb-bb, that's not a very easy question in fact. A solution might be to use UTC datetimes - those are not affected by daylight saving and are a good universal ways to represent dates without ambiguity. You can do all the processing using UTC, and then "translate back" to whatever time zone you were using. In your example I think you could probably  translate the timestamps into UTC datetimes to have more readable dates. Let me know if that solves your problem.

We need to work with known offsets in Darts because we need ways to extrapolate dates of future data points (when forecasting, or when doing "dates arithmetic" e.g. to align covariates with targets). Using pandas offsets is by far the most convenient because it's kind of universal, but it might be too limited to address all use-cases. We may consider at some point in the future to use another date system if we find a better one... We would need a very strong motivation though.
